import assert from 'node:assert/strict';import { mkdtemp,readFile,rm,writeFile } from 'node:fs/promises';import { createHash } from 'node:crypto';import os from 'node:os';import path from 'node:path';import test from 'node:test';import { validateRehearsalEvidence,validateRehearsalPlan } from '../scripts/rehearsal-contract.mjs';
const plan=JSON.parse(await readFile(new URL('../rehearsal-plan.json',import.meta.url),'utf8'));const current='a'.repeat(40),previous='b'.repeat(40),signer=`sha256:${'c'.repeat(64)}`;
function artifact(profile,sourceSha,evidenceKind='test-fixture'){return {profile,sourceSha,digest:`sha256:${(sourceSha===current?'d':'e').repeat(64)}`,appId:'com.agentsaas.mobile',version:sourceSha===current?'2.0.0':'1.9.0',buildNumber:profile==='ios-store'?(sourceSha===current?'200':'190'):null,versionCode:profile==='ios-store'?null:(sourceSha===current?200:190),signerDigest:signer,evidenceKind,m60EvidenceRef:evidenceKind==='test-fixture'?'fixture:explicit':(sourceSha===current?'current-release.json':'previous-release.json')};}
function outcome(action){if(action==='old_pending_same_protocol')return 'ack_unconfirmed_no_replay';if(action==='old_pending_protocol_upgrade')return 'failed_upgrade_no_replay';if(action==='store_pause_kill_compat_hotfix')return 'rollout_paused_capability_killed_metrics_verified_higher_version_hotfix';if(action==='enterprise_signed_rollback')return 'signed_verified_audited_replay_ledgered';return 'expected_invariant_verified';}
function bundle(mode='contract'){return {schemaVersion:'1.0.0',planId:'M70-02',mode,explicitContractMock:mode==='contract',commitSha:current,previousCommitSha:previous,caseResults:plan.cases.map((item,index)=>{const profile=item.platform==='ios'?'ios-store':item.action==='enterprise_signed_rollback'?'android-enterprise':'android-store';return {caseId:item.id,commitSha:current,device:{platform:item.platform,evidenceKind:mode==='contract'?'simulator':'real-device',provider:mode==='contract'?'contract-runner':'configured-provider',deviceId:`device-${index}`,model:'configured-model',osVersion:'configured-os'},previousArtifact:artifact(profile,previous,mode==='contract'?'test-fixture':'m60-verified-artifact'),currentArtifact:artifact(profile,current,mode==='contract'?'test-fixture':'m60-verified-artifact'),installMethod:item.installMethod,action:item.action,startedAt:'2026-09-01T08:30:00.000Z',completedAt:'2026-09-01T08:31:00.000Z',result:'passed',observedOutcome:outcome(item.action),receiptId:`receipt-${index}`,testRunId:`run-${index}`,log:{path:`evidence/${index}.log`,sha256:'0'.repeat(64)},screenshot:{path:`evidence/${index}.png`,sha256:'0'.repeat(64)}};})};}

const requireCache=new Map([['../schema/rehearsal-plan.schema.json',await readFile(new URL('../schema/rehearsal-plan.schema.json',import.meta.url),'utf8')],['../schema/rehearsal-evidence.schema.json',await readFile(new URL('../schema/rehearsal-evidence.schema.json',import.meta.url),'utf8')]]);function requireText(relative){return requireCache.get(relative);}
test('M70-02 plan is machine-valid with iOS/Android coverage and Android Enterprise',()=>{assert.deepEqual(validateRehearsalPlan(plan),{caseCount:21,ios:10,android:11});assert.doesNotThrow(()=>JSON.parse(requireText('../schema/rehearsal-plan.schema.json')));});
test('M70-02 explicit contract fixture validates but is never production evidence',async()=>{assert.equal((await validateRehearsalEvidence(bundle(),{plan})).passed,21);assert.doesNotThrow(()=>JSON.parse(requireText('../schema/rehearsal-evidence.schema.json')));});
async function rejects(name,mutate,pattern){await test(name,async()=>{const value=bundle();mutate(value);await assert.rejects(()=>validateRehearsalEvidence(value,{plan}),pattern);});}
await rejects('rejects tampered/cross SHA current artifact',v=>v.caseResults[0].currentArtifact.sourceSha='f'.repeat(40),/cross SHA/);
await rejects('rejects wrong signer upgrade chain',v=>v.caseResults[0].currentArtifact.signerDigest=`sha256:${'9'.repeat(64)}`,/wrong signer/);
await rejects('rejects version regression and Store downgrade',v=>{const item=v.caseResults.find(x=>x.action==='store_pause_kill_compat_hotfix'&&x.device.platform==='android');item.currentArtifact.versionCode=180;},/version regression\/store downgrade/);
await rejects('rejects missing action',v=>delete v.caseResults[0].action,/missing action/);
await rejects('rejects missing action time',v=>delete v.caseResults[0].startedAt,/missing startedAt/);
await rejects('rejects missing device',v=>delete v.caseResults[0].device,/missing device/);
await rejects('rejects missing artifact binding',v=>delete v.caseResults[0].currentArtifact,/missing currentArtifact/);
await rejects('rejects replayed receipt',v=>v.caseResults[1].receiptId=v.caseResults[0].receiptId,/receipt replay/);
await rejects('rejects pending protocol upgrade without failed_upgrade',v=>v.caseResults.find(x=>x.action==='old_pending_protocol_upgrade').observedOutcome='replayed',/fail without replay/);
await rejects('rejects Store rollback language instead of pause/kill/higher hotfix',v=>v.caseResults.find(x=>x.action==='store_pause_kill_compat_hotfix').observedOutcome='downgraded_store_binary',/store downgrade contract rejected/);
await rejects('rejects Enterprise rollback without audit ledger receipt',v=>v.caseResults.find(x=>x.action==='enterprise_signed_rollback').observedOutcome='installed',/enterprise audit missing/);
await rejects('rejects missing evidence hash',v=>v.caseResults[0].log.sha256='',/log missing sha256/);

test('production accepts only real devices, M60 artifacts and matching file hashes',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'m70-02-'));try{const value=bundle('production');const release=(sha)=>({commitOid:sha,profiles:['ios-store','android-store','android-enterprise'].map(profile=>artifact(profile,sha,'m60-verified-artifact')).map(item=>({profile:item.profile,artifactSha256:item.digest,appId:item.appId,version:item.version,buildNumber:item.buildNumber===null?null:Number(item.buildNumber),versionCode:item.versionCode,signerFingerprint:item.signerDigest}))});await writeFile(path.join(root,'current-release.json'),JSON.stringify(release(current)));await writeFile(path.join(root,'previous-release.json'),JSON.stringify(release(previous)));for(const [index,item] of value.caseResults.entries()){await writeFile(path.join(root,`${index}.log`),'log');await writeFile(path.join(root,`${index}.png`),'png');item.log.path=`${index}.log`;item.log.sha256=createHash('sha256').update('log').digest('hex');item.screenshot.path=`${index}.png`;item.screenshot.sha256=createHash('sha256').update('png').digest('hex');}assert.equal((await validateRehearsalEvidence(value,{plan,evidenceRoot:root,releaseEvidenceValidator:()=>{}})).passed,21);value.caseResults[0].log.sha256='f'.repeat(64);await assert.rejects(()=>validateRehearsalEvidence(value,{plan,evidenceRoot:root,releaseEvidenceValidator:()=>{}}),/hash mismatch/);value.caseResults[0].device.evidenceKind='simulator';await assert.rejects(()=>validateRehearsalEvidence(value,{plan,evidenceRoot:root,releaseEvidenceValidator:()=>{}}),/real device only/);}finally{await rm(root,{recursive:true,force:true});}});
