import type { CatalogScenarioPublic, WorkflowTraceEventV1 } from '@agent/shared';
import type { ReplayScript, ReplayStep } from './types';

export { TECHNICAL_INQUIRY_TRACE_SCENARIO_ID } from './technicalInquiryTraceMeta';

const workflowId = 'technical-inquiry-to-approved-quote-loop';
const instanceId = 'simulation-technical-inquiry-quote-001';
const common = { schemaVersion: 1 as const, workflowId, instanceId, authority: 'simulation' as const };

const planSteps = [
  { id: 'find-spec-conflict', title: '先发现不能靠猜的规格冲突', activeForm: '正在核对询价规格与库存' },
  { id: 'clarify-requirement', title: '保存冲突版本，再发最小澄清问题', activeForm: '正在准备最小澄清问题' },
  { id: 'resume-with-customer-answer', title: '客户答复后从原任务继续', activeForm: '正在读取客户答复并更新需求版本' },
  { id: 'draft-quote', title: '根据最新事实生成报价草案', activeForm: '正在计算报价与交付条件' },
  { id: 'approve-quote', title: '技术、商业与交付一起确认', activeForm: '正在核对组合审批边界' },
  { id: 'send-and-confirm-quote', title: '发送唯一获批版本并等待客户确认', activeForm: '正在跟踪报价送达与客户确认' },
  { id: 'approve-and-commit-order', title: '报价转订单前再次核对', activeForm: '正在复核并提交销售订单' },
  { id: 'verify-quote-order-terminal', title: '最终复查报价、订单和商机', activeForm: '正在执行跨系统终态核对' },
];

function rejectedEvents(sequence: number, stepId: string, gateId: string, title: string): WorkflowTraceEventV1[] {
  return [
    { ...common, id: `${gateId}-rejected`, sequence, type: 'gate_resolved', stepId, gateId, decision: 'rejected', message: '退回修改，未执行后续业务系统写入。' },
    {
      ...common,
      id: `${stepId}-waiting`,
      sequence: sequence + 1,
      type: 'step',
      stepId,
      status: 'waiting',
      outcome: { text: `${title}已退回，业务系统未写入`, tone: 'warn' },
      detail: [{ warn: '重新提交后仍需再次明确批准，不沿用本次决定。' }],
    },
  ];
}

const steps: ReplayStep[] = [
  {
    caption: '先发现不能靠猜的规格冲突',
    blocks: [],
    trace: {
      events: [
        { ...common, id: 'quote-plan', sequence: 10, type: 'plan', steps: planSteps },
        { ...common, id: 'find-spec-conflict-start', sequence: 11, type: 'step', stepId: 'find-spec-conflict', status: 'in_progress', activeForm: '正在核对询价规格与库存' },
        {
          ...common,
          id: 'find-spec-conflict-read',
          sequence: 12,
          type: 'activity',
          stepId: 'find-spec-conflict',
          activityId: 'read-rfq-sources',
          title: '同时读取客户消息、询价附件、商机和产品资料',
          status: 'success',
          system: '询价资料库',
          operation: '读取权威来源',
          detail: ['保留各来源原文和版本，不自动选择看起来更合理的一项。'],
        },
        {
          ...common,
          id: 'find-spec-conflict-effect',
          sequence: 13,
          type: 'effect',
          stepId: 'find-spec-conflict',
          effectId: 'rfq-source-conflict',
          effectType: 'source',
          system: '询价资料库',
          operation: 'read',
          title: '询价资料核对',
          summary: '发现 IP67 与 IP65 冲突，停止继续报价。',
          entity: { type: 'rfq', id: 'RFQ-SIM-2026-081' },
          fields: [
            { label: '客户消息', value: '防护等级 IP67', state: 'active' },
            { label: '询价附件', value: '防护等级 IP65', state: 'warning' },
            { label: '原型号库存', value: '0 件', state: 'warning' },
            { label: '替代型号库存', value: '36 件', state: 'success' },
          ],
          verification: 'simulated',
          evidenceRefs: ['simulation:RFQ-SIM-2026-081'],
        },
        {
          ...common,
          id: 'find-spec-conflict-done',
          sequence: 14,
          type: 'step',
          stepId: 'find-spec-conflict',
          status: 'completed',
          outcome: { text: '发现 1 项关键规格冲突，已停止继续报价', tone: 'warn', stat: [{ label: '冲突', value: '1 项' }, { label: '可用替代库存', value: '36 件' }] },
          display: [{
            type: 'comparison',
            title: '核对规格来源',
            items: [
              { label: '客户消息', value: 'IP67', note: '当前原文' },
              { label: '询价附件', value: 'IP65', note: '与消息冲突' },
            ],
          }],
          evidenceRefs: ['simulation:RFQ-SIM-2026-081'],
        },
      ],
    },
  },
  {
    caption: '保存冲突版本，再发最小澄清问题',
    blocks: [],
    trace: {
      events: [
        { ...common, id: 'clarify-requirement-start', sequence: 20, type: 'step', stepId: 'clarify-requirement', status: 'in_progress', activeForm: '正在准备最小澄清问题' },
        {
          ...common,
          id: 'clarify-version-saved',
          sequence: 21,
          type: 'activity',
          stepId: 'clarify-requirement',
          activityId: 'save-conflict-version',
          title: '保存包含来源的需求冲突版本',
          status: 'success',
          system: 'CRM',
          operation: '保存草稿',
          detail: [{ k: '发送状态', v: '尚未向客户发送' }],
        },
        {
          ...common,
          id: 'clarify-requirement-gate',
          sequence: 22,
          type: 'gate_requested',
          stepId: 'clarify-requirement',
          gateId: 'clarify-send-approval',
          title: '确认发送澄清',
          description: '这一步会向客户发送消息，必须由销售明确确认后才能继续。',
          facts: [
            { label: '防护等级', value: '请确认 IP65 或 IP67' },
            { label: '数量', value: '请确认本次数量' },
            { label: '替代许可', value: '是否接受认证兼容型号' },
          ],
          approveLabel: '确认发送澄清',
          rejectLabel: '退回修改',
        },
      ],
      approvedEvents: [
        { ...common, id: 'clarify-send-approved', sequence: 23, type: 'gate_resolved', stepId: 'clarify-requirement', gateId: 'clarify-send-approval', decision: 'approved' },
        {
          ...common,
          id: 'clarify-message-sent',
          sequence: 24,
          type: 'effect',
          stepId: 'clarify-requirement',
          effectId: 'clarification-message',
          effectType: 'communication',
          system: '企业邮箱',
          operation: 'send',
          title: '发送最小澄清问题',
          summary: '澄清消息已模拟送达测试联系人。',
          entity: { type: 'mail', id: 'MAIL-SIM-2026-02' },
          fields: [
            { label: '防护等级', value: '请确认 IP65 或 IP67', state: 'pending' },
            { label: '数量', value: '请确认本次数量', state: 'pending' },
            { label: '替代许可', value: '是否接受认证兼容型号', state: 'pending' },
          ],
          receipt: { id: 'MAIL-SIM-2026-02', system: '企业邮箱' },
          verification: 'simulated',
        },
        {
          ...common,
          id: 'clarify-requirement-done',
          sequence: 25,
          type: 'step',
          stepId: 'clarify-requirement',
          status: 'completed',
          outcome: { text: '澄清消息已获批并模拟送达，等待客户答复' },
          display: [{ type: 'facts', title: '已发送澄清', items: [{ label: '问题', value: '3 项' }, { label: '接收方', value: '测试联系人' }, { label: '状态', value: '模拟送达' }] }],
          evidenceRefs: ['simulation:MAIL-SIM-2026-02'],
        },
      ],
      rejectedEvents: rejectedEvents(23, 'clarify-requirement', 'clarify-send-approval', '澄清消息'),
    },
  },
  {
    caption: '客户答复后从原任务继续',
    blocks: [],
    trace: {
      events: [
        { ...common, id: 'resume-with-customer-answer-start', sequence: 30, type: 'step', stepId: 'resume-with-customer-answer', status: 'in_progress', activeForm: '正在读取客户答复并更新需求版本' },
        {
          ...common,
          id: 'customer-answer-read',
          sequence: 31,
          type: 'effect',
          stepId: 'resume-with-customer-answer',
          effectId: 'customer-answer',
          effectType: 'communication',
          system: '钉钉',
          operation: 'read',
          title: '读取客户澄清答复',
          summary: '客户已确认规格、数量和替代许可。',
          entity: { type: 'message', id: 'MSG-SIM-2026-03' },
          fields: [
            { label: '销售', value: '请确认防护等级、数量以及是否接受兼容替代。', state: 'neutral' },
            { label: '客户', value: '需要 IP67，共 20 件，可接受认证兼容替代。', state: 'success' },
          ],
          verification: 'simulated',
        },
        {
          ...common,
          id: 'requirement-version-updated',
          sequence: 32,
          type: 'effect',
          stepId: 'resume-with-customer-answer',
          effectId: 'requirement-v2',
          effectType: 'record',
          system: 'CRM',
          operation: 'update',
          title: '更新需求版本',
          entity: { type: 'requirement', id: 'REQ-SIM-V2' },
          fields: [
            { label: '防护等级', value: 'IP67', before: '待澄清', state: 'success' },
            { label: '数量', value: '20 件', before: '待澄清', state: 'success' },
            { label: '替代许可', value: '接受认证兼容型号', before: '待澄清', state: 'success' },
          ],
          receipt: { id: 'REQ-SIM-V2', system: 'CRM' },
          verification: 'simulated',
        },
        {
          ...common,
          id: 'resume-with-customer-answer-done',
          sequence: 33,
          type: 'step',
          stepId: 'resume-with-customer-answer',
          status: 'completed',
          outcome: { text: '需求已锁定为 IP67、20 件，并允许认证兼容替代型号' },
          display: [{ type: 'list', title: '已确认需求清单', items: [{ label: '防护等级', value: 'IP67', note: '以客户最新答复为准' }, { label: '数量', value: '20 件' }, { label: '替代许可', value: '允许认证兼容型号' }] }],
          evidenceRefs: ['simulation:MSG-SIM-2026-03', 'simulation:REQ-SIM-V2'],
        },
      ],
    },
  },
  {
    caption: '根据最新事实生成报价草案',
    blocks: [],
    trace: {
      events: [
        { ...common, id: 'draft-quote-start', sequence: 40, type: 'step', stepId: 'draft-quote', status: 'in_progress', activeForm: '正在计算报价与交付条件' },
        {
          ...common,
          id: 'draft-quote-calculate',
          sequence: 41,
          type: 'activity',
          stepId: 'draft-quote',
          activityId: 'calculate-quote',
          title: '重新读取产品、价格和库存并计算报价',
          status: 'success',
          system: 'ERP',
          operation: '确定性计算',
          detail: ['金额、税费、毛利和交期由确定性服务计算。'],
        },
        {
          ...common,
          id: 'draft-quote-created',
          sequence: 42,
          type: 'effect',
          stepId: 'draft-quote',
          effectId: 'quote-draft',
          effectType: 'record',
          system: 'ERP',
          operation: 'create',
          title: '创建报价草案',
          entity: { type: 'quote', id: 'Q-SIM-2026-081' },
          fields: [
            { label: '型号与数量', value: '认证替代型号 × 20', state: 'success' },
            { label: '含税金额', value: '¥22,600 · 税率 13%', state: 'active' },
            { label: '付款条件', value: '30% 预付 / 70% 发货前', state: 'neutral' },
            { label: '交付日期', value: '2026-08-18', state: 'neutral' },
          ],
          receipt: { id: 'Q-SIM-2026-081', system: 'ERP' },
          verification: 'simulated',
        },
        {
          ...common,
          id: 'draft-quote-done',
          sequence: 43,
          type: 'step',
          stepId: 'draft-quote',
          status: 'completed',
          outcome: { text: '报价草案已生成，含税金额 ¥22,600，交付日期 2026-08-18' },
          display: [{ type: 'facts', title: '报价草案', items: [{ label: '含税金额', value: '¥22,600' }, { label: '付款条件', value: '30% / 70%' }, { label: '交付日期', value: '2026-08-18' }] }],
          evidenceRefs: ['simulation:Q-SIM-2026-081'],
        },
      ],
    },
  },
  {
    caption: '技术、商业与交付一起确认',
    blocks: [],
    trace: {
      events: [
        { ...common, id: 'approve-quote-start', sequence: 50, type: 'step', stepId: 'approve-quote', status: 'in_progress', activeForm: '正在核对组合审批边界' },
        {
          ...common,
          id: 'approve-quote-preread',
          sequence: 51,
          type: 'activity',
          stepId: 'approve-quote',
          activityId: 'recheck-quote-snapshot',
          title: '重新读取产品、价格、库存与报价版本',
          status: 'success',
          system: 'ERP',
          operation: '审批前回读',
        },
        {
          ...common,
          id: 'approve-quote-gate',
          sequence: 52,
          type: 'gate_requested',
          stepId: 'approve-quote',
          gateId: 'quote-combined-approval',
          title: '批准当前报价版本',
          description: '审批绑定当前报价和库存快照，任一关键事实变化都会使本次批准失效。',
          facts: [
            { label: '技术兼容', value: '待技术负责人确认' },
            { label: '利润与价格', value: '待商业负责人确认' },
            { label: '库存与交期', value: '待交付负责人确认' },
            { label: '对外发送', value: '待销售负责人确认' },
          ],
          approveLabel: '批准当前报价版本',
          rejectLabel: '退回修改',
        },
      ],
      approvedEvents: [
        { ...common, id: 'quote-combined-approved', sequence: 53, type: 'gate_resolved', stepId: 'approve-quote', gateId: 'quote-combined-approval', decision: 'approved' },
        {
          ...common,
          id: 'quote-approval-recorded',
          sequence: 54,
          type: 'effect',
          stepId: 'approve-quote',
          effectId: 'quote-approval',
          effectType: 'record',
          system: '审批中心',
          operation: 'approve',
          title: '记录报价组合审批',
          entity: { type: 'approval', id: 'APR-SIM-2026-05' },
          fields: [
            { label: '技术兼容', value: '已确认', state: 'success' },
            { label: '利润与价格', value: '已确认', state: 'success' },
            { label: '库存与交期', value: '已确认', state: 'success' },
            { label: '对外发送', value: '已确认', state: 'success' },
          ],
          receipt: { id: 'APR-SIM-2026-05', system: '审批中心' },
          verification: 'simulated',
        },
        {
          ...common,
          id: 'approve-quote-done',
          sequence: 55,
          type: 'step',
          stepId: 'approve-quote',
          status: 'completed',
          outcome: { text: '技术、商业、交付和对外发送 4 项确认均已通过', stat: [{ label: '通过', value: '4/4' }] },
          display: [{ type: 'checklist', title: '组合审批结果', items: [{ label: '技术兼容', status: 'pass' }, { label: '利润与价格', status: 'pass' }, { label: '库存与交期', status: 'pass' }, { label: '对外发送', status: 'pass' }] }],
          evidenceRefs: ['simulation:APR-SIM-2026-05'],
        },
      ],
      rejectedEvents: rejectedEvents(53, 'approve-quote', 'quote-combined-approval', '报价版本'),
    },
  },
  {
    caption: '发送唯一获批版本并等待客户确认',
    blocks: [],
    trace: {
      events: [
        { ...common, id: 'send-and-confirm-quote-start', sequence: 60, type: 'step', stepId: 'send-and-confirm-quote', status: 'in_progress', activeForm: '正在跟踪报价送达与客户确认' },
        {
          ...common,
          id: 'approved-quote-sent',
          sequence: 61,
          type: 'effect',
          stepId: 'send-and-confirm-quote',
          effectId: 'approved-quote-mail',
          effectType: 'communication',
          system: '企业邮箱',
          operation: 'send',
          title: '发送唯一获批报价版本',
          summary: '获批报价版本 ¥22,600 已模拟送达。',
          entity: { type: 'mail', id: 'MAIL-SIM-2026-06' },
          fields: [{ label: '已发送', value: '获批报价版本 · ¥22,600', state: 'success' }],
          receipt: { id: 'MAIL-SIM-2026-06', system: '企业邮箱' },
          verification: 'simulated',
        },
        {
          ...common,
          id: 'customer-quote-confirmation',
          sequence: 62,
          type: 'effect',
          stepId: 'send-and-confirm-quote',
          effectId: 'customer-quote-confirmation',
          effectType: 'communication',
          system: '企业邮箱',
          operation: 'read',
          title: '读取客户报价确认',
          summary: '客户确认接受当前报价及交付条件。',
          entity: { type: 'mail', id: 'MAIL-SIM-REPLY-06' },
          fields: [
            { label: '客户回复', value: '确认接受当前报价及交付条件', state: 'success' },
            { label: '关联状态', value: '回复已绑定唯一报价版本', state: 'active' },
          ],
          verification: 'simulated',
        },
        {
          ...common,
          id: 'send-and-confirm-quote-done',
          sequence: 63,
          type: 'step',
          stepId: 'send-and-confirm-quote',
          status: 'completed',
          outcome: { text: '客户已接受唯一获批报价版本，金额、型号、付款与交期无偏差' },
          display: [{ type: 'checklist', title: '客户确认核对', items: [{ label: '报价金额', status: 'pass', value: '¥22,600' }, { label: '型号数量', status: 'pass', value: '替代型号 × 20' }, { label: '付款条件', status: 'pass', value: '30% / 70%' }, { label: '交付日期', status: 'pass', value: '2026-08-18' }] }],
          evidenceRefs: ['simulation:MAIL-SIM-2026-06', 'simulation:MAIL-SIM-REPLY-06'],
        },
      ],
    },
  },
  {
    caption: '报价转订单前再次核对',
    blocks: [],
    trace: {
      events: [
        { ...common, id: 'approve-and-commit-order-start', sequence: 70, type: 'step', stepId: 'approve-and-commit-order', status: 'in_progress', activeForm: '正在复核并提交销售订单' },
        {
          ...common,
          id: 'order-preread',
          sequence: 71,
          type: 'activity',
          stepId: 'approve-and-commit-order',
          activityId: 'recheck-order-inputs',
          title: '重新读取库存、价格、客户确认和报价版本',
          status: 'success',
          system: 'ERP',
          operation: '提交前回读',
        },
        {
          ...common,
          id: 'order-commit-gate',
          sequence: 72,
          type: 'gate_requested',
          stepId: 'approve-and-commit-order',
          gateId: 'order-commit-approval',
          title: '批准并提交销售订单',
          description: '订单内容与客户接受的报价一致，但正式写入 ERP 前仍需有权人确认。',
          facts: [
            { label: '型号与数量', value: '认证替代型号 × 20' },
            { label: '订单金额', value: '¥22,600' },
            { label: '交付日期', value: '2026-08-18' },
          ],
          approveLabel: '批准并提交订单',
          rejectLabel: '退回修改',
        },
      ],
      approvedEvents: [
        { ...common, id: 'order-commit-approved', sequence: 73, type: 'gate_resolved', stepId: 'approve-and-commit-order', gateId: 'order-commit-approval', decision: 'approved' },
        {
          ...common,
          id: 'sales-order-created',
          sequence: 74,
          type: 'effect',
          stepId: 'approve-and-commit-order',
          effectId: 'sales-order',
          effectType: 'record',
          system: 'ERP',
          operation: 'create',
          title: '创建正式销售订单',
          entity: { type: 'sales_order', id: 'SO-SIM-2026-081' },
          fields: [
            { label: '订单状态', value: '已提交', before: '等待最终批准', state: 'success' },
            { label: '型号与数量', value: '认证替代型号 × 20', state: 'success' },
            { label: '订单金额', value: '¥22,600', state: 'success' },
            { label: '交付日期', value: '2026-08-18', state: 'success' },
          ],
          receipt: { id: 'SO-SIM-2026-081', system: 'ERP' },
          verification: 'simulated',
        },
        {
          ...common,
          id: 'sales-order-verified',
          sequence: 75,
          type: 'effect',
          stepId: 'approve-and-commit-order',
          effectId: 'sales-order-verification',
          effectType: 'verification',
          system: 'ERP',
          operation: 'verify',
          title: '模拟回读销售订单',
          summary: '订单内容与客户接受的报价一致。',
          entity: { type: 'sales_order', id: 'SO-SIM-2026-081' },
          fields: [{ label: '销售订单', value: 'SO-SIM-2026-081 · 内容一致', state: 'success' }],
          verification: 'simulated',
        },
        {
          ...common,
          id: 'approve-and-commit-order-done',
          sequence: 76,
          type: 'step',
          stepId: 'approve-and-commit-order',
          status: 'completed',
          outcome: { text: '销售订单已模拟写入并核对一致', stat: [{ label: '订单', value: '1 份' }, { label: '差异', value: '0 项' }] },
          display: [{ type: 'facts', title: '订单提交结果', items: [{ label: '订单号', value: 'SO-SIM-2026-081' }, { label: '金额', value: '¥22,600' }, { label: '状态', value: '模拟写入并核对' }] }],
          evidenceRefs: ['simulation:SO-SIM-2026-081'],
        },
      ],
      rejectedEvents: rejectedEvents(73, 'approve-and-commit-order', 'order-commit-approval', '销售订单'),
    },
  },
  {
    caption: '最终复查报价、订单和商机',
    blocks: [],
    trace: {
      events: [
        { ...common, id: 'verify-quote-order-terminal-start', sequence: 80, type: 'step', stepId: 'verify-quote-order-terminal', status: 'in_progress', activeForm: '正在执行跨系统终态核对' },
        {
          ...common,
          id: 'opportunity-next-step-updated',
          sequence: 81,
          type: 'effect',
          stepId: 'verify-quote-order-terminal',
          effectId: 'opportunity-next-step',
          effectType: 'record',
          system: 'CRM',
          operation: 'update',
          title: '更新商机下一步',
          entity: { type: 'opportunity', id: 'OPP-SIM-2026-081' },
          fields: [{ label: '商机下一步', value: '订单履约', before: '报价跟进', state: 'success' }],
          receipt: { id: 'OPP-SIM-2026-081', system: 'CRM' },
          verification: 'simulated',
        },
        {
          ...common,
          id: 'quote-order-terminal-verified',
          sequence: 82,
          type: 'effect',
          stepId: 'verify-quote-order-terminal',
          effectId: 'terminal-verification',
          effectType: 'verification',
          system: '跨系统回读',
          operation: 'verify',
          title: '最终复查报价、订单和商机',
          summary: '没有未决审批或等待，重复执行不会创建第二份订单。',
          entity: { type: 'workflow_terminal', id: 'TERMINAL-SIM-081' },
          fields: [
            { label: '需求', value: '规格冲突已澄清并保留版本', state: 'success' },
            { label: '报价', value: '唯一获批版本已送达并接受', state: 'success' },
            { label: '订单', value: '已提交并模拟核对一致', state: 'success' },
            { label: '商机', value: '下一步已更新为订单履约', state: 'success' },
          ],
          verification: 'simulated',
        },
        {
          ...common,
          id: 'verify-quote-order-terminal-done',
          sequence: 83,
          type: 'step',
          stepId: 'verify-quote-order-terminal',
          status: 'completed',
          outcome: { text: '需求、报价、订单和商机 4 项终态全部一致', stat: [{ label: '一致', value: '4/4' }, { label: '未决', value: '0' }] },
          display: [{ type: 'checklist', title: '跨系统终态核对', items: [{ label: '需求版本', status: 'pass', value: '冲突已澄清' }, { label: '报价版本', status: 'pass', value: '唯一版本已接受' }, { label: '销售订单', status: 'pass', value: '模拟核对一致' }, { label: '商机下一步', status: 'pass', value: '订单履约' }] }],
          evidenceRefs: ['simulation:TERMINAL-SIM-081'],
        },
      ],
    },
  },
];

export function buildTechnicalInquiryTraceScript(scenario: CatalogScenarioPublic): ReplayScript {
  const entry = scenario.launch.entry;
  const entryTitle = entry.kind === 'scheduled_trigger'
    ? '定时任务触发'
    : entry.kind === 'business_event'
      ? '业务事件'
      : '用户消息';
  return {
    scenarioId: scenario.id,
    title: scenario.title,
    mode: 'hero',
    traceEntryEvents: [{
      ...common,
      id: 'technical-inquiry-entry',
      sequence: 0,
      type: 'entry',
      entryKind: entry.kind,
      title: entryTitle,
      content: entry.content,
    }],
    steps,
    sources: [
      { blockRef: 'trace.step1.sources', producer: '企业资料与库存连接器', state: 'needs-change', gap: '当前为 simulation fixture；真实运行需由连接器返回来源版本与库存事实。' },
      { blockRef: 'trace.step2.clarification', producer: '企业邮箱连接器', state: 'needs-change', gap: '当前为 simulation fixture；真实运行需返回消息 ID 与送达回执。' },
      { blockRef: 'trace.step3.requirement', producer: 'CRM 连接器', state: 'needs-change', gap: '当前为 simulation fixture；真实运行需返回需求版本 ID。' },
      { blockRef: 'trace.step4.quote', producer: 'ERP 连接器', state: 'needs-change', gap: '当前为 simulation fixture；真实运行需返回报价草案 ID。' },
      { blockRef: 'trace.step5.approval', producer: '平台 Interaction/EventStore', state: 'exists' },
      { blockRef: 'trace.step6.customer-confirmation', producer: '企业邮箱连接器', state: 'needs-change', gap: '当前为 simulation fixture；真实运行需关联客户回复与报价版本。' },
      { blockRef: 'trace.step7.order', producer: 'ERP 连接器', state: 'needs-change', gap: '当前为 simulation fixture；真实运行需返回订单 ID 并独立回读。' },
      { blockRef: 'trace.step8.terminal', producer: 'Workflow Trace projector', state: 'needs-change', gap: '当前为 simulation fixture；真实运行需汇合 CRM、ERP 与交互事实。' },
    ],
  };
}
