import { describe, expect, it, vi } from 'vitest';
import { evaluateCapability } from '@agent/shared';
import { enterOfflineLocalShell, runMobileRecoveryAction } from './authConnectionCapabilityAdapter';
const normal = evaluateCapability({ userId: 'u', tenantId: 't', provider: 'p', channel: 'mobile', correlationId: 'c', observedAt: 'now', providerConfigured: true, callbackDomainConfigured: true, ssoAvailable: true, credential: 'valid', network: 'online', server: 'healthy', tenantAllowed: true, operation: 'connection' });
describe('mobile capability adapter', () => {
  it('offline/biometric shell remains local and blocks sensitive work', () => expect(enterOfflineLocalShell(normal, 'later', 'offline')).toMatchObject({ authoritative: false, affectedCapabilities: expect.arrayContaining(['messaging.send', 'connection.refresh']), allowedActions: ['open_readonly_local_shell', 'retry_later'] }));
  it('user cancellation never opens system browser', async () => { const open = vi.fn(); const fallback = { ...normal, mode: 'degraded' as const, allowedActions: ['use_system_browser_sso' as const] }; await runMobileRecoveryAction({ action: 'use_system_browser_sso', status: fallback, confirmLeavingApp: async () => false, openSystemBrowser: open, revalidate: async () => normal }); expect(open).not.toHaveBeenCalled(); });
  it('confirmed browser fallback opens exactly once', async () => { const open = vi.fn(); const fallback = { ...normal, mode: 'degraded' as const, allowedActions: ['use_system_browser_sso' as const] }; await runMobileRecoveryAction({ action: 'use_system_browser_sso', status: fallback, confirmLeavingApp: async () => true, openSystemBrowser: open, revalidate: async () => normal }); expect(open).toHaveBeenCalledOnce(); });
  it('normal recovery requires server revalidation result', async () => { const expired = { ...normal, mode: 'degraded' as const, allowedActions: ['reauthenticate' as const], requiresServerRevalidation: true }; const revalidate = vi.fn().mockResolvedValue(normal); await expect(runMobileRecoveryAction({ action: 'reauthenticate', status: expired, confirmLeavingApp: async () => true, openSystemBrowser: vi.fn(), revalidate })).resolves.toBe(normal); expect(revalidate).toHaveBeenCalledOnce(); });
});
