import { Router, type Request, type Response } from 'express';
import type { SessionAutomationCommandService } from '../runtime/sessionAutomationCommandService.js';
import { SessionAutomationConflictError, type PgSessionAutomationStore } from '../runtime/sessionAutomationStore.js';
export interface SessionAutomationsRouterOptions { store:PgSessionAutomationStore;service:SessionAutomationCommandService; }
function identity(req:Request,sessionId:string){if(!req.user?.sub||!req.user.tenantId)throw new SessionAutomationConflictError('FORBIDDEN','Authentication required');return{tenantId:req.user.tenantId,ownerUserId:req.user.sub,sessionId};}
function sendError(res:Response,error:unknown):void{if(error instanceof SessionAutomationConflictError){const status=error.code==='NOT_FOUND'?404:error.code==='FORBIDDEN'?403:error.code==='INVALID_COMMAND'?400:error.code==='FEATURE_DISABLED'||error.code==='EXECUTION_DISABLED'?503:409;res.status(status).json({code:error.code,message:error.message,current:error.current});return;}res.status(500).json({code:'INTERNAL_ERROR',message:error instanceof Error?error.message:'unknown error'});}
export function createSessionAutomationsRouter(options:SessionAutomationsRouterOptions):Router{const router=Router({mergeParams:true});
 router.get('/sessions/:sessionId/automations',async(req,res)=>{try{const id=identity(req,req.params.sessionId!);res.json({items:(await options.store.list(id.tenantId,id.sessionId)).filter(x=>x.ownerUserId===id.ownerUserId)});}catch(e){sendError(res,e);}});
 router.get('/sessions/:sessionId/automations/:automationId',async(req,res)=>{try{const id=identity(req,req.params.sessionId!);const item=await options.store.get(id.tenantId,id.sessionId,req.params.automationId!);if(!item||item.ownerUserId!==id.ownerUserId)throw new SessionAutomationConflictError('NOT_FOUND','automation 不存在');res.json(item);}catch(e){sendError(res,e);}});
 router.post('/sessions/:sessionId/automations/commands',async(req,res)=>{try{const id=identity(req,req.params.sessionId!);const body=req.body as Record<string,unknown>;if(typeof body.clientMessageId!=='string'||typeof body.command!=='string')throw new SessionAutomationConflictError('INVALID_COMMAND','clientMessageId/command required');res.json(await options.service.command(id,{clientMessageId:body.clientMessageId,command:body.command,...(typeof body.expectedControlVersion==='number'?{expectedControlVersion:body.expectedControlVersion}:{}),...(typeof body.expectedIncarnationId==='string'?{expectedIncarnationId:body.expectedIncarnationId}:{})}));}catch(e){sendError(res,e);}});
 router.post('/sessions/:sessionId/automations/:automationId/control',async(req,res)=>{try{const id=identity(req,req.params.sessionId!);const body=req.body as Record<string,unknown>;if(typeof body.clientMessageId!=='string'||typeof body.action!=='string'||typeof body.expectedControlVersion!=='number'||typeof body.expectedIncarnationId!=='string')throw new SessionAutomationConflictError('INVALID_COMMAND','control fence required');if(!['pause','resume','run','clear','reconcile'].includes(body.action))throw new SessionAutomationConflictError('INVALID_COMMAND','invalid action');res.json(await options.service.control(id,req.params.automationId!,body as never));}catch(e){sendError(res,e);}});return router;}
