import { z } from 'zod';
import type { ScheduleWakeupInput, UpdateGoalInput } from '@agent/shared/types/sessionAutomation.js';
import type { AuthorizedToolCall, ToolCallContext, ToolDescriptor, ToolProvider, ToolResult } from '../toolRuntime.js';
import type { PgSessionAutomationStore } from '../../runtime/sessionAutomationStore.js';
import type { SessionAutomationEvaluator } from '../../runtime/sessionAutomationEvaluator.js';

export interface SessionAutomationFence { automationId:string;incarnationId:string;generation:number;specVersion:number;executionId:string; }
const scheduleSchema=z.object({action:z.enum(['schedule','stop']),delayMs:z.number().int().optional(),reason:z.string().max(1000).optional()});
const goalSchema=z.object({action:z.enum(['continue','blocked','complete_candidate']),summary:z.string().min(1).max(8000),evidenceRefs:z.array(z.string().min(1).max(1000)).max(50).optional()});
export const scheduleWakeupToolDescriptor:ToolDescriptor={id:'ScheduleWakeup',name:'ScheduleWakeup',displayName:'Schedule wakeup',description:'For this automation execution only: schedule the next adaptive continuation or stop it. The host supplies the immutable automation fence.',schema:scheduleSchema,risk:'safe',approvalMode:'never',auditCategory:'session_automation',category:'session',label:'安排续跑'};
export const updateGoalToolDescriptor:ToolDescriptor={id:'UpdateGoal',name:'UpdateGoal',displayName:'Update goal',description:'For this goal automation execution only: continue, report blocked, or nominate a completion candidate with evidence. A separate evaluator decides completion.',schema:goalSchema,risk:'safe',approvalMode:'never',auditCategory:'session_automation',category:'session',label:'更新目标'};

export class SessionAutomationTools {
 constructor(readonly store:PgSessionAutomationStore,readonly evaluator?:SessionAutomationEvaluator){}
 async scheduleWakeup(input:ScheduleWakeupInput & {tenantId:string;sessionId:string}):Promise<{accepted:boolean;reason?:string}>{return this.store.tx(async c=>{const current=await this.store.getLocked(c,input.tenantId,input.sessionId,input.automationId).catch(()=>undefined);if(!current)return{accepted:false,reason:'not_found'};if(current.spec.kind!=='loop'||current.spec.mode!=='adaptive')return{accepted:false,reason:'not_adaptive'};if(current.incarnationId!==input.incarnationId||current.generation!==input.generation||current.specVersion!==input.specVersion||current.activeRunId!==input.runId)return{accepted:false,reason:'stale_fence'};if(input.action==='stop'){await c.query(`UPDATE ${this.store.tables.automations} SET status='completed',phase='terminal',active_run_id=NULL,control_version=control_version+1 WHERE automation_id=$1`,[input.automationId]);return{accepted:true};}if(!input.delayMs||input.delayMs<60_000||input.delayMs>86_400_000)return{accepted:false,reason:'delay_out_of_range'};const epoch=Date.now();await c.query(`UPDATE ${this.store.tables.wakeups} SET state='superseded' WHERE tenant_id=$1 AND automation_id=$2 AND state IN ('pending','claimed')`,[current.tenantId,current.automationId]);await c.query(`UPDATE ${this.store.tables.automations} SET continuation_epoch=$3 WHERE tenant_id=$1 AND automation_id=$2`,[current.tenantId,current.automationId,epoch]);await this.store.scheduleTx(c,{tenantId:current.tenantId,sessionId:current.sessionId,automationId:current.automationId,incarnationId:current.incarnationId,generation:current.generation,specVersion:current.specVersion,continuationEpoch:epoch,triggerKey:`adaptive:${current.automationId}:g${current.generation}:e${epoch}:from:${input.runId}`,dueAt:new Date(Date.now()+input.delayMs),payload:{reason:input.reason}});return{accepted:true};});}
 async updateGoal(input:UpdateGoalInput & {tenantId:string;sessionId:string;executionId:string}):Promise<{accepted:boolean;reason?:string}>{const current=await this.store.get(input.tenantId,input.sessionId,input.automationId);if(!current||current.spec.kind!=='goal')return{accepted:false,reason:'not_found'};if(current.incarnationId!==input.incarnationId||current.generation!==input.generation||current.specVersion!==input.specVersion||current.activeRunId!==input.runId)return{accepted:false,reason:'stale_fence'};if(input.action==='complete_candidate'){if(!this.evaluator)return{accepted:false,reason:'evaluator_unavailable'};const result=await this.evaluator.nominate({...input,executionId:input.executionId,evidenceRefs:input.evidenceRefs??[]});return{accepted:result.queued,reason:result.reason};}if(input.action==='blocked'){await this.store.pool.query(`UPDATE ${this.store.tables.automations} SET status='blocked',phase='idle',active_run_id=NULL,control_version=control_version+1 WHERE tenant_id=$1 AND automation_id=$2 AND generation=$3`,[input.tenantId,input.automationId,input.generation]);return{accepted:true};}const epoch=Date.now();await this.store.tx(async c=>{await c.query(`UPDATE ${this.store.tables.wakeups} SET state='superseded' WHERE tenant_id=$1 AND automation_id=$2 AND state IN ('pending','claimed')`,[current.tenantId,current.automationId]);await c.query(`UPDATE ${this.store.tables.automations} SET continuation_epoch=$3 WHERE tenant_id=$1 AND automation_id=$2`,[current.tenantId,current.automationId,epoch]);await this.store.scheduleTx(c,{tenantId:current.tenantId,sessionId:current.sessionId,automationId:current.automationId,incarnationId:current.incarnationId,generation:current.generation,specVersion:current.specVersion,continuationEpoch:epoch,triggerKey:`goal:${current.automationId}:g${current.generation}:e${epoch}:from:${input.runId}`,dueAt:new Date(),payload:{summary:input.summary}});});return{accepted:true};}
}

export class SessionAutomationToolProvider implements ToolProvider {
 constructor(private readonly tools:SessionAutomationTools){}
 list(context?:ToolCallContext):ToolDescriptor[]{const fence=context?.automationFence;if(!fence||context?.runId!==fence.runId)return[];return[scheduleWakeupToolDescriptor,updateGoalToolDescriptor];}
 async invoke<T>(call:AuthorizedToolCall<T>,context:ToolCallContext):Promise<ToolResult|undefined>{const fence=context.automationFence;if(!fence||!context.runId||!context.sessionId)return undefined;const tenantId=context.channelContext.sessionOwner?.tenantId??context.channelContext.user?.tenantId;if(!tenantId)return{content:JSON.stringify({accepted:false,reason:'missing_tenant'})};let result;if(call.toolId==='ScheduleWakeup'){const input=scheduleSchema.parse(call.input);result=await this.tools.scheduleWakeup({...input,...fence,tenantId,sessionId:context.sessionId,runId:context.runId});}else if(call.toolId==='UpdateGoal'){const input=goalSchema.parse(call.input);result=await this.tools.updateGoal({...input,...fence,tenantId,sessionId:context.sessionId,runId:context.runId});}else return undefined;return{content:JSON.stringify(result)};}
}
