import { createHash, randomUUID } from 'node:crypto';
import type pg from 'pg';
import type { SessionAutomationSnapshot, SessionAutomationSpec } from '@agent/shared/types/sessionAutomation.js';
import { applySessionAutomationSchema, sessionAutomationTables, type SessionAutomationTables } from './sessionAutomationStoreSchema.js';

type Pool = pg.Pool;
type Client = pg.PoolClient;
export interface AutomationIdentity { tenantId: string; sessionId: string; ownerUserId: string; }

export interface ClaimedDispatch { outboxId: string; wakeupId: string; automationId: string; tenantId: string; sessionId: string; targetRunId: string; triggerKey: string; payload: Record<string, unknown>; leaseToken: string; generation: number; specVersion: number; incarnationId: string; }
export class SessionAutomationConflictError extends Error { constructor(readonly code: string, message: string, readonly current?: SessionAutomationSnapshot) { super(message); } }

export class PgSessionAutomationStore {
  readonly tables: SessionAutomationTables;
  constructor(readonly pool: Pool, readonly tablePrefix = 'runtime', readonly runsTable = `${tablePrefix}_runs`) { this.tables = sessionAutomationTables(tablePrefix); }
  async init(): Promise<void> {
    const client = await this.pool.connect(); const key = `${this.tables.automations}:init`;
    try { await client.query('SELECT pg_advisory_lock(hashtext($1))',[key]); await client.query('BEGIN'); await applySessionAutomationSchema(client,this.tablePrefix,this.runsTable); await client.query('COMMIT'); }
    catch (e) { await client.query('ROLLBACK').catch(()=>undefined); throw e; }
    finally { await client.query('SELECT pg_advisory_unlock(hashtext($1))',[key]).catch(()=>undefined); client.release(); }
  }
  async tx<T>(fn:(client:Client)=>Promise<T>):Promise<T>{ const c=await this.pool.connect(); try{await c.query('BEGIN');const v=await fn(c);await c.query('COMMIT');return v;}catch(e){await c.query('ROLLBACK').catch(()=>undefined);throw e;}finally{c.release();} }
  private map(row: Record<string,unknown>): SessionAutomationSnapshot {
    const spec = row.spec as SessionAutomationSpec;
    return { automationId:String(row.automation_id),incarnationId:String(row.incarnation_id),tenantId:String(row.tenant_id),sessionId:String(row.session_id),ownerUserId:String(row.owner_user_id),status:row.status as SessionAutomationSnapshot['status'],phase:row.phase as SessionAutomationSnapshot['phase'],generation:Number(row.generation),specVersion:Number(row.spec_version),controlVersion:Number(row.control_version),projectionVersion:Number(row.projection_version),spec,nextWakeupAt:row.next_wakeup_at ? new Date(String(row.next_wakeup_at)).toISOString():undefined,activeRunId:row.active_run_id ? String(row.active_run_id):undefined,runCount:Number(row.run_count),noProgressCount:Number(row.no_progress_count),lastError:row.last_error ? String(row.last_error):undefined,createdAt:new Date(String(row.created_at)).toISOString(),updatedAt:new Date(String(row.updated_at)).toISOString() };
  }
  private selectSql():string { const t=this.tables; return `SELECT a.*,s.spec FROM ${t.automations} a JOIN ${t.specs} s ON s.automation_id=a.automation_id AND s.spec_version=a.spec_version WHERE a.tenant_id=$1 AND a.session_id=$2`; }
  async list(tenantId:string,sessionId:string):Promise<SessionAutomationSnapshot[]>{const r=await this.pool.query(this.selectSql(),[tenantId,sessionId]);return r.rows.map((x)=>this.map(x));}
  async get(tenantId:string,sessionId:string,automationId:string):Promise<SessionAutomationSnapshot|undefined>{const r=await this.pool.query(`${this.selectSql()} AND a.automation_id=$3`,[tenantId,sessionId,automationId]);return r.rows[0]?this.map(r.rows[0]):undefined;}
  async getLive(client:Client,tenantId:string,sessionId:string):Promise<SessionAutomationSnapshot|undefined>{const r=await client.query(`${this.selectSql()} AND a.status IN ('active','paused','blocked','completing','cancelling','reconcile_required') FOR UPDATE OF a`,[tenantId,sessionId]);return r.rows[0]?this.map(r.rows[0]):undefined;}
  async getLocked(client:Client,tenantId:string,sessionId:string,automationId:string):Promise<SessionAutomationSnapshot|undefined>{const r=await client.query(`${this.selectSql()} AND a.automation_id=$3 FOR UPDATE OF a`,[tenantId,sessionId,automationId]);return r.rows[0]?this.map(r.rows[0]):undefined;}
  async findCommand(client:Client,id:AutomationIdentity,clientMessageId:string,commandDigest:string):Promise<unknown|undefined>{await client.query('SELECT pg_advisory_xact_lock(hashtext($1),hashtext($2))',[id.tenantId+':'+id.ownerUserId,clientMessageId]);const r=await client.query(`SELECT command_digest,response FROM ${this.tables.commands} WHERE tenant_id=$1 AND owner_user_id=$2 AND client_message_id=$3 FOR UPDATE`,[id.tenantId,id.ownerUserId,clientMessageId]);if(!r.rows[0])return undefined;if(r.rows[0].command_digest!==commandDigest)throw new SessionAutomationConflictError('CONFLICT','clientMessageId 已用于不同命令');return r.rows[0].response;}
  async recordCommand(client:Client,id:AutomationIdentity,sessionId:string,clientMessageId:string,digest:string,automationId:string|undefined,response:unknown):Promise<void>{await client.query(`INSERT INTO ${this.tables.commands}(tenant_id,owner_user_id,client_message_id,session_id,command_digest,automation_id,response) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id.tenantId,id.ownerUserId,clientMessageId,sessionId,digest,automationId??null,JSON.stringify(response)]);}
  async create(client:Client,id:AutomationIdentity,spec:SessionAutomationSpec,now:Date):Promise<SessionAutomationSnapshot>{
    const automationId=randomUUID(),incarnationId=randomUUID(), digest=specDigest(spec);
    await client.query(`INSERT INTO ${this.tables.automations}(automation_id,tenant_id,session_id,owner_user_id,incarnation_id,kind,mode,status,phase) VALUES($1,$2,$3,$4,$5,$6,$7,'active','waiting')`,[automationId,id.tenantId,id.sessionId,id.ownerUserId,incarnationId,spec.kind,spec.mode]);
    await client.query(`INSERT INTO ${this.tables.specs}(automation_id,tenant_id,session_id,spec_version,spec_digest,spec) VALUES($1,$2,$3,1,$4,$5)`,[automationId,id.tenantId,id.sessionId,digest,JSON.stringify(spec)]);
    const due=spec.mode==='fixed'?new Date(now.getTime()+spec.intervalMs!):now; await this.scheduleTx(client,{tenantId:id.tenantId,sessionId:id.sessionId,automationId,incarnationId,generation:1,specVersion:1,continuationEpoch:1,triggerKey:`initial:${automationId}:g1:e1`,dueAt:due,payload:{spec}});
    const created=await this.getLocked(client,id.tenantId,id.sessionId,automationId); if(!created)throw new Error('automation insert lost'); await this.event(client,created,'created',{}); return created;
  }
  async replace(client:Client,current:SessionAutomationSnapshot,spec:SessionAutomationSpec):Promise<SessionAutomationSnapshot>{
    const incarnationId=randomUUID(),generation=current.generation+1,specVersion=current.specVersion+1;
    await client.query(`UPDATE ${this.tables.wakeups} SET state='superseded' WHERE tenant_id=$1 AND automation_id=$2 AND state IN ('pending','claimed')`,[current.tenantId,current.automationId]);
    await client.query(`UPDATE ${this.tables.automations} SET incarnation_id=$3,kind=$4,mode=$5,status='active',phase='waiting',generation=$6,spec_version=$7,control_version=control_version+1,projection_version=projection_version+1,continuation_epoch=1,updated_at=now() WHERE tenant_id=$1 AND automation_id=$2`,[current.tenantId,current.automationId,incarnationId,spec.kind,spec.mode,generation,specVersion]);
    await client.query(`INSERT INTO ${this.tables.specs}(automation_id,tenant_id,session_id,spec_version,spec_digest,spec) VALUES($1,$2,$3,$4,$5,$6)`,[current.automationId,current.tenantId,current.sessionId,specVersion,specDigest(spec),JSON.stringify(spec)]);
    const due=spec.mode==='fixed'?new Date(Date.now()+spec.intervalMs!):new Date(); await this.scheduleTx(client,{tenantId:current.tenantId,sessionId:current.sessionId,automationId:current.automationId,incarnationId,generation,specVersion,continuationEpoch:1,triggerKey:`initial:${current.automationId}:g${generation}:e1`,dueAt:due,payload:{spec}});
    return (await this.getLocked(client,current.tenantId,current.sessionId,current.automationId))!;
  }
  async control(client:Client,current:SessionAutomationSnapshot,action:'pause'|'resume'|'run'|'clear'|'reconcile'):Promise<SessionAutomationSnapshot>{
    let status=current.status,phase=current.phase,generation=current.generation,epoch=0;
    if(action==='pause'){status='paused';phase='idle';generation++;await client.query(`UPDATE ${this.tables.wakeups} SET state='superseded' WHERE tenant_id=$1 AND automation_id=$2 AND state IN ('pending','claimed')`,[current.tenantId,current.automationId]);}
    if(action==='resume'){if(!['paused','blocked'].includes(status))throw new SessionAutomationConflictError('CONFLICT','仅 paused/blocked 可 resume',current);status='active';phase='waiting';generation++;epoch=1;}
    if(action==='clear'){status=current.activeRunId?'cancelling':'cancelled';phase=current.activeRunId?'running':'terminal';generation++;await client.query(`UPDATE ${this.tables.wakeups} SET state='superseded' WHERE tenant_id=$1 AND automation_id=$2 AND state IN ('pending','claimed')`,[current.tenantId,current.automationId]);}
    if(action==='reconcile'&&status!=='reconcile_required')throw new SessionAutomationConflictError('CONFLICT','当前无需 reconcile',current);
    await client.query(`UPDATE ${this.tables.automations} SET status=$3,phase=$4,generation=$5,control_version=control_version+1,projection_version=projection_version+1,continuation_epoch=continuation_epoch+$6,updated_at=now() WHERE tenant_id=$1 AND automation_id=$2`,[current.tenantId,current.automationId,status,phase,generation,epoch]);
    const next=(await this.getLocked(client,current.tenantId,current.sessionId,current.automationId))!;
    if(action==='resume'||action==='run')await this.scheduleTx(client,{tenantId:next.tenantId,sessionId:next.sessionId,automationId:next.automationId,incarnationId:next.incarnationId,generation:next.generation,specVersion:next.specVersion,continuationEpoch:epoch||Number(Date.now()),triggerKey:action==='run'?`manual:${next.automationId}:g${next.generation}:${randomUUID()}`:`initial:${next.automationId}:g${next.generation}:e${epoch}`,dueAt:new Date(),payload:{spec:next.spec}});
    await this.event(client,next,action,{}); return (await this.getLocked(client,next.tenantId,next.sessionId,next.automationId))!;
  }
  async scheduleTx(client:Client,input:{tenantId:string;sessionId:string;automationId:string;incarnationId:string;generation:number;specVersion:number;continuationEpoch:number;triggerKey:string;dueAt:Date;payload:unknown}):Promise<string>{const id=randomUUID();await client.query(`INSERT INTO ${this.tables.wakeups}(wakeup_id,tenant_id,session_id,automation_id,incarnation_id,generation,spec_version,continuation_epoch,trigger_key,due_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(tenant_id,automation_id,trigger_key) DO NOTHING`,[id,input.tenantId,input.sessionId,input.automationId,input.incarnationId,input.generation,input.specVersion,input.continuationEpoch,input.triggerKey,input.dueAt]);await client.query(`UPDATE ${this.tables.automations} SET next_wakeup_at=LEAST(COALESCE(next_wakeup_at,$3),$3),phase='waiting',updated_at=now() WHERE tenant_id=$1 AND automation_id=$2`,[input.tenantId,input.automationId,input.dueAt]);return id;}
  async claimDue(limit=25,leaseMs=30_000):Promise<number>{return this.tx(async c=>{const r=await c.query(`SELECT w.* FROM ${this.tables.wakeups} w JOIN ${this.tables.automations} a USING(automation_id) WHERE w.state='pending' AND w.due_at<=now() AND a.status='active' AND a.generation=w.generation AND a.incarnation_id=w.incarnation_id ORDER BY w.due_at FOR UPDATE OF w SKIP LOCKED LIMIT $1`,[limit]);for(const w of r.rows){const outboxId=randomUUID(),targetRunId=deterministicRunId(w.tenant_id,w.session_id,w.trigger_key);await c.query(`UPDATE ${this.tables.wakeups} SET state='claimed',lease_token=$2,lease_expires_at=now()+($3::text||' milliseconds')::interval,attempt_count=attempt_count+1 WHERE wakeup_id=$1`,[w.wakeup_id,randomUUID(),leaseMs]);await c.query(`INSERT INTO ${this.tables.outbox}(outbox_id,wakeup_id,tenant_id,session_id,automation_id,incarnation_id,generation,spec_version,continuation_epoch,trigger_key,target_run_id,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(tenant_id,wakeup_id) DO NOTHING`,[outboxId,w.wakeup_id,w.tenant_id,w.session_id,w.automation_id,w.incarnation_id,w.generation,w.spec_version,w.continuation_epoch,w.trigger_key,targetRunId,JSON.stringify({automationId:w.automation_id,triggerKey:w.trigger_key})]);}return r.rowCount??0;});}
  async claimDispatch(limit=10,leaseMs=30_000):Promise<ClaimedDispatch[]>{return this.tx(async c=>{const r=await c.query(`SELECT o.* FROM ${this.tables.outbox} o JOIN ${this.tables.automations} a USING(automation_id) WHERE o.state='pending' AND o.next_attempt_at<=now() AND a.status='active' AND a.generation=o.generation AND a.incarnation_id=o.incarnation_id ORDER BY o.created_at FOR UPDATE OF o SKIP LOCKED LIMIT $1`,[limit]);const result:ClaimedDispatch[]=[];for(const o of r.rows){const token=randomUUID();await c.query(`UPDATE ${this.tables.outbox} SET state='dispatching',lease_token=$2,lease_expires_at=now()+($3::text||' milliseconds')::interval,attempt_count=attempt_count+1 WHERE outbox_id=$1`,[o.outbox_id,token,leaseMs]);result.push({outboxId:o.outbox_id,wakeupId:o.wakeup_id,automationId:o.automation_id,tenantId:o.tenant_id,sessionId:o.session_id,targetRunId:o.target_run_id,triggerKey:o.trigger_key,payload:o.payload,leaseToken:token,generation:Number(o.generation),specVersion:Number(o.spec_version),incarnationId:o.incarnation_id});}return result;});}
  async markDispatched(item:ClaimedDispatch):Promise<void>{await this.tx(async c=>{const r=await c.query(`UPDATE ${this.tables.outbox} o SET state='dispatched',lease_expires_at=NULL FROM ${this.tables.automations} a WHERE o.outbox_id=$1 AND o.lease_token=$2 AND o.state='dispatching' AND a.automation_id=o.automation_id AND a.generation=o.generation AND a.incarnation_id=o.incarnation_id RETURNING o.*`,[item.outboxId,item.leaseToken]);if(!r.rows[0])throw new SessionAutomationConflictError('STALE_GENERATION','dispatch fence lost');await c.query(`INSERT INTO ${this.tables.executions}(execution_id,tenant_id,session_id,automation_id,incarnation_id,generation,spec_version,outbox_id,run_id,state) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'running') ON CONFLICT(outbox_id) DO NOTHING`,[item.outboxId,item.tenantId,item.sessionId,item.automationId,item.incarnationId,item.generation,item.specVersion,item.outboxId,item.targetRunId]);await c.query(`UPDATE ${this.tables.automations} SET phase='running',active_run_id=$3,next_wakeup_at=NULL,run_count=run_count+1,projection_version=projection_version+1,updated_at=now() WHERE tenant_id=$1 AND automation_id=$2`,[item.tenantId,item.automationId,item.targetRunId]);});}
  async failDispatch(item:ClaimedDispatch,error:unknown):Promise<void>{await this.pool.query(`UPDATE ${this.tables.outbox} SET state=CASE WHEN attempt_count>=5 THEN 'dead' ELSE 'pending' END,next_attempt_at=now()+interval '30 seconds',lease_token=NULL,lease_expires_at=NULL,last_error=$3 WHERE outbox_id=$1 AND lease_token=$2`,[item.outboxId,item.leaseToken,error instanceof Error?error.message:String(error)]);}
  async recoverLeases():Promise<void>{await this.tx(async c=>{await c.query(`UPDATE ${this.tables.wakeups} SET state='pending',lease_token=NULL,lease_expires_at=NULL WHERE state='claimed' AND lease_expires_at<now() AND NOT EXISTS(SELECT 1 FROM ${this.tables.outbox} o WHERE o.wakeup_id=${this.tables.wakeups}.wakeup_id)`);await c.query(`UPDATE ${this.tables.outbox} SET state=CASE WHEN attempt_count>=5 THEN 'dead' ELSE 'pending' END,lease_token=NULL,lease_expires_at=NULL,last_error=COALESCE(last_error,'dispatch_lease_expired') WHERE state='dispatching' AND lease_expires_at<now()`);});}
  async event(c:Client,s:SessionAutomationSnapshot,type:string,payload:unknown):Promise<void>{await c.query(`INSERT INTO ${this.tables.events}(automation_event_id,tenant_id,session_id,automation_id,generation,spec_version,control_version,projection_version,event_type,event_payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[randomUUID(),s.tenantId,s.sessionId,s.automationId,s.generation,s.specVersion,s.controlVersion,s.projectionVersion,type,JSON.stringify(payload)]);}
}
export function specDigest(spec:SessionAutomationSpec):string{return createHash('sha256').update(JSON.stringify(spec)).digest('hex');}
export function commandDigest(command:string):string{return createHash('sha256').update(command.trim()).digest('hex');}
export function deterministicRunId(tenantId:string,sessionId:string,triggerKey:string):string{const hex=createHash('sha256').update(`${tenantId}\0${sessionId}\0${triggerKey}`).digest('hex');return `${hex.slice(0,8)}-${hex.slice(8,12)}-5${hex.slice(13,16)}-a${hex.slice(17,20)}-${hex.slice(20,32)}`;}
