import { parseSessionAutomationCommand } from '@agent/shared';
import type { SessionAutomationAttachment, SessionAutomationCommandResponse, SessionAutomationControlAction, SessionAutomationControlRequest, SessionAutomationSnapshot } from '@agent/shared';
import { commandDigest, PgSessionAutomationStore, SessionAutomationConflictError, type AutomationIdentity, type SessionAutomationReconciliationEvidence } from './sessionAutomationStore.js';
import type { SessionAutomationFeatureFlags, SessionAutomationFlagSource } from './sessionAutomationFlags.js';

export interface SessionAutomationCommandAuthorizer { authorize(id:AutomationIdentity):Promise<{maxCredits?:number}|void>; }
type CommandResult=SessionAutomationCommandResponse&{cursor?:string|null}; // cursor is committed with the command receipt

export class SessionAutomationCommandService {
 private authorizer?:SessionAutomationCommandAuthorizer;
 constructor(readonly store:PgSessionAutomationStore,private readonly flagSource:SessionAutomationFlagSource,authorizer?:SessionAutomationCommandAuthorizer){this.authorizer=authorizer;}
 setAuthorizer(authorizer:SessionAutomationCommandAuthorizer):void{this.authorizer=authorizer;}
 private async authorize(id:AutomationIdentity):Promise<{maxCredits?:number}>{if(!this.authorizer)throw new SessionAutomationConflictError('GOVERNANCE_UNAVAILABLE','automation governance unavailable');return (await this.authorizer.authorize(id))??{};}
 async command(id:AutomationIdentity,input:{clientMessageId:string;command:string;expectedControlVersion?:number;expectedIncarnationId?:string;attachments?:SessionAutomationAttachment[];requestDigest?:string;canonicalRequest?:Record<string,unknown>}):Promise<CommandResult>{
  const parsed = parseSessionAutomationCommand(input.command);if(parsed === null)throw new SessionAutomationConflictError('INVALID_COMMAND','不是 automation 命令');
  const flags=this.flagSource.read();const executionDisabledAction=!['status','pause','clear','reconcile'].includes(parsed.action);
  if(!flags.executionEnabled&&executionDisabledAction)throw new SessionAutomationConflictError('EXECUTION_DISABLED','execution kill switch 已关闭');
  const shutdownAction=['status','pause','clear'].includes(parsed.action);
  if(!shutdownAction&&!flags.controlEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','Session automation control disabled');
  const canonicalRequest=input.canonicalRequest??{command:input.command.trim(),sessionId:id.sessionId};const digest=input.requestDigest??commandDigest(canonicalRequest);
  const receipt=await this.store.getCommandReceipt?.(id.tenantId,id.ownerUserId,input.clientMessageId);
  if(receipt){if(receipt.commandDigest!==digest||receipt.sessionId!==id.sessionId)throw new SessionAutomationConflictError('CONFLICT','clientMessageId 已用于不同命令');if(receipt.state==='committed'&&receipt.response)return{...receipt.response,result:'idempotent_replay',cursor:receipt.cursor};}
  if(input.attachments?.length&&!('spec' in parsed))throw new SessionAutomationConflictError('INVALID_COMMAND','attachments 仅可用于 create/replace');
  if('spec' in parsed&&input.attachments?.length)parsed.spec.attachments=input.attachments;
  const authorization=parsed.action!=='status'&&parsed.action!=='list'?await this.authorize(id):{};
  if ('spec' in parsed && authorization.maxCredits !== undefined) {
    parsed.spec.budget.maxCredits = Math.min(parsed.spec.budget.maxCredits ?? authorization.maxCredits, authorization.maxCredits);
  }
  const result=await this.store.tx(async c=>{const replay=await this.store.findCommand(c,id,input.clientMessageId,digest);if(replay?.response)return {...replay.response as SessionAutomationCommandResponse,result:'idempotent_replay' as const,cursor:replay.cursor};
   const live=await this.store.getLiveForOwner(c,id);let response:SessionAutomationCommandResponse;
   if(parsed.action==='status'||parsed.action==='list'){response={result:'status',snapshot:live};}
   else if(['pause','resume','run','clear'].includes(parsed.action)){if(!live||live.ownerUserId!==id.ownerUserId)throw new SessionAutomationConflictError('NOT_FOUND','没有活动 automation');this.assertFence(live,input);if(['resume','run'].includes(parsed.action))this.assertExecutionEnabled();response={result:'updated',snapshot:await this.store.control(c,live,parsed.action as SessionAutomationControlAction)};}
   else if(parsed.action==='reconcile'){throw new SessionAutomationConflictError('INVALID_COMMAND','reconcile is restricted to authoritative internal APIs');}
   else {if(!('spec' in parsed))throw new SessionAutomationConflictError('INVALID_COMMAND','命令缺少 spec');if(live&&live.ownerUserId!==id.ownerUserId)throw new SessionAutomationConflictError('NOT_FOUND','没有活动 automation');if(live&&parsed.action==='create')throw new SessionAutomationConflictError('CONFIRM_REPLACE_REQUIRED','已有活动 automation，需显式 replace',live);if(live){this.assertNotDraining(live);this.assertFence(live,input);this.assertFeature(parsed.spec.mode,this.flagSource.read());response={result:'updated',snapshot:await this.store.replace(c,live,parsed.spec)};}else{this.assertFeature(parsed.spec.mode,this.flagSource.read());response={result:'created',snapshot:await this.store.create(c,id,parsed.spec,new Date(),()=>this.flagSource.read().executionEnabled)};}}
   const cursor=await this.store.recordCommand(c,id,id.sessionId,input.clientMessageId,digest,response.snapshot?.automationId,response,canonicalRequest);return{...response,cursor};});
  if(result.snapshot)this.store.publish(result.snapshot,'automation_command_ack');return result;
 }
 async edit(id:AutomationIdentity,automationId:string,input:{clientMessageId:string;payload:Record<string,unknown>;expectedControlVersion:number;expectedIncarnationId:string}):Promise<CommandResult>{
  const flags=this.flagSource.read();if(!flags.executionEnabled)throw new SessionAutomationConflictError('EXECUTION_DISABLED','execution kill switch 已关闭');if(!flags.controlEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','Session automation control disabled');const authorization=await this.authorize(id);
  const canonicalRequest={type:'edit',sessionId:id.sessionId,automationId,...input};const digest=commandDigest(canonicalRequest);
  const result=await this.store.tx(async c=>{const replay=await this.store.findCommand(c,id,input.clientMessageId,digest);if(replay?.response)return{...replay.response as SessionAutomationCommandResponse,result:'idempotent_replay' as const,cursor:replay.cursor};const current=await this.store.getLockedForOwner(c,id,automationId);if(!current||current.ownerUserId!==id.ownerUserId)throw new SessionAutomationConflictError('NOT_FOUND','automation 不存在');this.assertNotDraining(current);this.assertFence(current,input);
   const rawBudget=input.payload.budget;const patch:Record<string,number|string>={};
   if(rawBudget&&typeof rawBudget==='object'&&!Array.isArray(rawBudget)){for(const key of ['maxRuns','maxTurns','maxTokens','maxCredits'] as const){const value=(rawBudget as Record<string,unknown>)[key];if(value!==undefined){if(typeof value!=='number'||!Number.isFinite(value)||value<=0||(key!=='maxCredits'&&!Number.isSafeInteger(value)))throw new SessionAutomationConflictError('INVALID_COMMAND',`${key} 必须为正数`);patch[key]=value;}}const expiresAt=(rawBudget as Record<string,unknown>).expiresAt;if(expiresAt!==undefined){const time=typeof expiresAt==='string'?Date.parse(expiresAt):NaN;if(!Number.isFinite(time)||time<=Date.now())throw new SessionAutomationConflictError('INVALID_COMMAND','expiresAt 必须为未来时间');patch.expiresAt=new Date(time).toISOString();}}
   if(authorization.maxCredits!==undefined)patch.maxCredits=Math.min(typeof patch.maxCredits==='number'?patch.maxCredits:current.spec.budget.maxCredits??authorization.maxCredits,authorization.maxCredits);
   const value=current.spec.kind==='goal'?input.payload.condition:input.payload.prompt;const hasText=typeof value==='string'&&value.trim().length>0;const hasBudget=Object.keys(patch).length>0;if(!hasText&&!hasBudget)throw new SessionAutomationConflictError('INVALID_COMMAND','edit 需要提示词/条件或 budget');
   const spec={...current.spec,...(hasText?(current.spec.kind==='goal'?{condition:(value as string).trim()}:{prompt:(value as string).trim()}):{}),budget:{...current.spec.budget,...patch}};this.assertExecutionEnabled();const response={result:'updated' as const,snapshot:await this.store.replace(c,current,spec)};const cursor=await this.store.recordCommand(c,id,id.sessionId,input.clientMessageId,digest,automationId,response,canonicalRequest);return{...response,cursor};});if(result.snapshot)this.store.publish(result.snapshot);return result;
 }
 async control(id:AutomationIdentity,automationId:string,input:SessionAutomationControlRequest):Promise<CommandResult>{
  const flags=this.flagSource.read();if(!flags.executionEnabled&&!['pause','clear','reconcile'].includes(input.action))throw new SessionAutomationConflictError('EXECUTION_DISABLED','execution kill switch 已关闭');if(!['pause','clear'].includes(input.action)&&!flags.controlEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','Session automation control disabled');await this.authorize(id);const canonicalRequest={type:'control',sessionId:id.sessionId,automationId,...input};const digest=commandDigest(canonicalRequest);
  const result=await this.store.tx(async c=>{const replay=await this.store.findCommand(c,id,input.clientMessageId,digest);if(replay?.response)return{...replay.response as SessionAutomationCommandResponse,result:'idempotent_replay' as const,cursor:replay.cursor};const current=await this.store.getLockedForOwner(c,id,automationId);if(!current||current.ownerUserId!==id.ownerUserId)throw new SessionAutomationConflictError('NOT_FOUND','automation 不存在');this.assertFence(current,input);if(!['pause','clear','reconcile'].includes(input.action))this.assertExecutionEnabled();const response={result:'updated' as const,snapshot:await this.store.control(c,current,input.action)};const cursor=await this.store.recordCommand(c,id,id.sessionId,input.clientMessageId,digest,automationId,response,canonicalRequest);return{...response,cursor};});
  if(result.snapshot)this.store.publish(result.snapshot);return result;
 }
 async reconcileAuthoritatively(id:AutomationIdentity,automationId:string,input:{clientMessageId:string;expectedControlVersion:number;expectedIncarnationId:string;evidence:SessionAutomationReconciliationEvidence}):Promise<CommandResult>{
  if(!['provider_adapter','operator'].includes(input.evidence.receiptAuthority))throw new SessionAutomationConflictError('FORBIDDEN','authoritative reconciliation receipt required');
  const canonicalRequest={type:'internal_reconcile',sessionId:id.sessionId,automationId,clientMessageId:input.clientMessageId,expectedControlVersion:input.expectedControlVersion,expectedIncarnationId:input.expectedIncarnationId,evidence:input.evidence};const digest=commandDigest(canonicalRequest);
  const result=await this.store.tx(async c=>{const replay=await this.store.findCommand(c,id,input.clientMessageId,digest);if(replay?.response)return{...replay.response as SessionAutomationCommandResponse,result:'idempotent_replay' as const,cursor:replay.cursor};const current=await this.store.getLockedForOwner(c,id,automationId);if(!current||current.ownerUserId!==id.ownerUserId)throw new SessionAutomationConflictError('NOT_FOUND','automation 不存在');this.assertFence(current,input);const response={result:'updated' as const,snapshot:await this.store.control(c,current,'reconcile',input.evidence)};const cursor=await this.store.recordCommand(c,id,id.sessionId,input.clientMessageId,digest,automationId,response,canonicalRequest);return{...response,cursor};});
  if(result.snapshot)this.store.publish(result.snapshot);return result;
 }
 private assertExecutionEnabled():void{if(!this.flagSource.read().executionEnabled)throw new SessionAutomationConflictError('EXECUTION_DISABLED','execution kill switch 已关闭');}
 private assertNotDraining(current:SessionAutomationSnapshot):void{if(['completed','cancelled','failed','expired'].includes(current.status))throw new SessionAutomationConflictError('CONFLICT','terminal automation 不可 edit/replace',current);if(['completing','cancelling','reconcile_required'].includes(current.status))throw new SessionAutomationConflictError('AUTOMATION_DRAINING','automation 正在收口，暂不可 edit/replace',current);}
 private assertFeature(mode:string,flags:SessionAutomationFeatureFlags):void{if(!flags.executionEnabled)throw new SessionAutomationConflictError('EXECUTION_DISABLED','execution kill switch 已关闭');if(mode==='fixed'&&!flags.fixedLoopEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','fixed loop disabled');if(mode==='adaptive'&&!flags.adaptiveLoopEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','adaptive loop disabled');if(mode==='goal'&&(!flags.goalEnabled||!flags.evaluatorEnforced))throw new SessionAutomationConflictError('FEATURE_DISABLED','goal evaluator is not fail-closed');}
 private assertFence(current:SessionAutomationSnapshot,input:{expectedControlVersion?:number;expectedIncarnationId?:string}):void{if(input.expectedControlVersion!==undefined&&input.expectedControlVersion!==current.controlVersion)throw new SessionAutomationConflictError('STALE_CONTROL_VERSION','controlVersion 已变化',current);if(input.expectedIncarnationId!==undefined&&input.expectedIncarnationId!==current.incarnationId)throw new SessionAutomationConflictError('STALE_CONTROL_VERSION','incarnation 已变化',current);}
}
