import { parseSessionAutomationCommand } from '@agent/shared';
import type { SessionAutomationCommandResponse, SessionAutomationControlAction, SessionAutomationControlRequest, SessionAutomationSnapshot } from '@agent/shared';
import { commandDigest, PgSessionAutomationStore, SessionAutomationConflictError, type AutomationIdentity, type SessionAutomationReconciliationEvidence } from './sessionAutomationStore.js';

export interface SessionAutomationFeatureFlags { controlEnabled:boolean;executionEnabled:boolean;fixedLoopEnabled:boolean;adaptiveLoopEnabled:boolean;goalEnabled:boolean;evaluatorEnforced:boolean; }
export interface SessionAutomationCommandAuthorizer { authorize(id:AutomationIdentity):Promise<void>; }
export const DEFAULT_SESSION_AUTOMATION_FLAGS:SessionAutomationFeatureFlags={controlEnabled:false,executionEnabled:false,fixedLoopEnabled:false,adaptiveLoopEnabled:false,goalEnabled:false,evaluatorEnforced:false};
type CommandResult=SessionAutomationCommandResponse&{cursor?:string|null}; // cursor is committed with the command receipt

export class SessionAutomationCommandService {
 private authorizer?:SessionAutomationCommandAuthorizer;
 constructor(readonly store:PgSessionAutomationStore,readonly flags:SessionAutomationFeatureFlags,authorizer?:SessionAutomationCommandAuthorizer){this.authorizer=authorizer;}
 setAuthorizer(authorizer:SessionAutomationCommandAuthorizer):void{this.authorizer=authorizer;}
 private async authorize(id:AutomationIdentity):Promise<void>{if(!this.authorizer)throw new SessionAutomationConflictError('GOVERNANCE_UNAVAILABLE','automation governance unavailable');await this.authorizer.authorize(id);}
 async command(id:AutomationIdentity,input:{clientMessageId:string;command:string;expectedControlVersion?:number;expectedIncarnationId?:string;requestDigest?:string;canonicalRequest?:Record<string,unknown>}):Promise<CommandResult>{
  const parsed = parseSessionAutomationCommand(input.command);if(parsed === null)throw new SessionAutomationConflictError('INVALID_COMMAND','不是 automation 命令');
  const shutdownAction=['status','list','pause','clear'].includes(parsed.action);
  if(!shutdownAction&&!this.flags.controlEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','Session automation control disabled');
  if(['resume','run'].includes(parsed.action)&&!this.flags.executionEnabled)throw new SessionAutomationConflictError('EXECUTION_DISABLED','execution kill switch 已关闭');
  const digest=input.requestDigest??commandDigest(input.command);const canonicalRequest=input.canonicalRequest??{command:input.command.trim()};
  if(parsed.action!=='status'&&parsed.action!=='list')await this.authorize(id);
  const result=await this.store.tx(async c=>{const replay=await this.store.findCommand(c,id,input.clientMessageId,digest);if(replay?.response)return {...replay.response as SessionAutomationCommandResponse,result:'idempotent_replay' as const,cursor:replay.cursor};
   const live=await this.store.getLiveForOwner(c,id);let response:SessionAutomationCommandResponse;
   if(parsed.action==='status'||parsed.action==='list'){response={result:'status',snapshot:live};}
   else if(['pause','resume','run','clear'].includes(parsed.action)){if(!live||live.ownerUserId!==id.ownerUserId)throw new SessionAutomationConflictError('NOT_FOUND','没有活动 automation');this.assertFence(live,input);response={result:'updated',snapshot:await this.store.control(c,live,parsed.action as SessionAutomationControlAction)};}
   else if(parsed.action==='reconcile'){throw new SessionAutomationConflictError('INVALID_COMMAND','reconcile is restricted to authoritative internal APIs');}
   else {if(!('spec' in parsed))throw new SessionAutomationConflictError('INVALID_COMMAND','命令缺少 spec');this.assertFeature(parsed.spec.mode);if(live&&live.ownerUserId!==id.ownerUserId)throw new SessionAutomationConflictError('NOT_FOUND','没有活动 automation');if(live&&parsed.action==='create')throw new SessionAutomationConflictError('CONFIRM_REPLACE_REQUIRED','已有活动 automation，需显式 replace',live);if(live){this.assertFence(live,input);response={result:'updated',snapshot:await this.store.replace(c,live,parsed.spec)};}else{response={result:'created',snapshot:await this.store.create(c,id,parsed.spec,new Date())};}}
   const cursor=await this.store.recordCommand(c,id,id.sessionId,input.clientMessageId,digest,response.snapshot?.automationId,response,canonicalRequest);return{...response,cursor};});
  if(result.snapshot)this.store.publish(result.snapshot,'automation_command_ack');return result;
 }
 async edit(id:AutomationIdentity,automationId:string,input:{clientMessageId:string;payload:Record<string,unknown>;expectedControlVersion:number;expectedIncarnationId:string}):Promise<CommandResult>{if(!this.flags.controlEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','Session automation control disabled');await this.authorize(id);const canonicalRequest={type:'edit',automationId,...input};const digest=commandDigest(canonicalRequest);const result=await this.store.tx(async c=>{const replay=await this.store.findCommand(c,id,input.clientMessageId,digest);if(replay?.response)return{...replay.response as SessionAutomationCommandResponse,result:'idempotent_replay' as const,cursor:replay.cursor};const current=await this.store.getLockedForOwner(c,id,automationId);if(!current||current.ownerUserId!==id.ownerUserId)throw new SessionAutomationConflictError('NOT_FOUND','automation 不存在');this.assertFence(current,input);const value=current.spec.kind==='goal'?input.payload.condition:input.payload.prompt;if(typeof value!=='string'||!value.trim())throw new SessionAutomationConflictError('INVALID_COMMAND','edit payload required');const spec={...current.spec,...(current.spec.kind==='goal'?{condition:value.trim()}:{prompt:value.trim()})};const response={result:'updated' as const,snapshot:await this.store.replace(c,current,spec)};const cursor=await this.store.recordCommand(c,id,id.sessionId,input.clientMessageId,digest,automationId,response,canonicalRequest);return{...response,cursor};});if(result.snapshot)this.store.publish(result.snapshot);return result;}
 async control(id:AutomationIdentity,automationId:string,input:SessionAutomationControlRequest):Promise<CommandResult>{
  if(!['pause','clear'].includes(input.action)&&!this.flags.controlEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','Session automation control disabled');if(['resume','run'].includes(input.action)&&!this.flags.executionEnabled)throw new SessionAutomationConflictError('EXECUTION_DISABLED','execution kill switch 已关闭');await this.authorize(id);const canonicalRequest={type:'control',automationId,...input};const digest=commandDigest(canonicalRequest);
  const result=await this.store.tx(async c=>{const replay=await this.store.findCommand(c,id,input.clientMessageId,digest);if(replay?.response)return{...replay.response as SessionAutomationCommandResponse,result:'idempotent_replay' as const,cursor:replay.cursor};const current=await this.store.getLockedForOwner(c,id,automationId);if(!current||current.ownerUserId!==id.ownerUserId)throw new SessionAutomationConflictError('NOT_FOUND','automation 不存在');this.assertFence(current,input);const response={result:'updated' as const,snapshot:await this.store.control(c,current,input.action)};const cursor=await this.store.recordCommand(c,id,id.sessionId,input.clientMessageId,digest,automationId,response,canonicalRequest);return{...response,cursor};});
  if(result.snapshot)this.store.publish(result.snapshot);return result;
 }
 async reconcileAuthoritatively(id:AutomationIdentity,automationId:string,input:{clientMessageId:string;expectedControlVersion:number;expectedIncarnationId:string;evidence:SessionAutomationReconciliationEvidence}):Promise<CommandResult>{
  if(!['provider_adapter','operator'].includes(input.evidence.receiptAuthority))throw new SessionAutomationConflictError('FORBIDDEN','authoritative reconciliation receipt required');
  const canonicalRequest={type:'internal_reconcile',automationId,clientMessageId:input.clientMessageId,expectedControlVersion:input.expectedControlVersion,expectedIncarnationId:input.expectedIncarnationId,evidence:input.evidence};const digest=commandDigest(canonicalRequest);
  const result=await this.store.tx(async c=>{const replay=await this.store.findCommand(c,id,input.clientMessageId,digest);if(replay?.response)return{...replay.response as SessionAutomationCommandResponse,result:'idempotent_replay' as const,cursor:replay.cursor};const current=await this.store.getLockedForOwner(c,id,automationId);if(!current||current.ownerUserId!==id.ownerUserId)throw new SessionAutomationConflictError('NOT_FOUND','automation 不存在');this.assertFence(current,input);const response={result:'updated' as const,snapshot:await this.store.control(c,current,'reconcile',input.evidence)};const cursor=await this.store.recordCommand(c,id,id.sessionId,input.clientMessageId,digest,automationId,response,canonicalRequest);return{...response,cursor};});
  if(result.snapshot)this.store.publish(result.snapshot);return result;
 }
 private assertFeature(mode:string):void{if(!this.flags.executionEnabled)throw new SessionAutomationConflictError('EXECUTION_DISABLED','execution kill switch 已关闭');if(mode==='fixed'&&!this.flags.fixedLoopEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','fixed loop disabled');if(mode==='adaptive'&&!this.flags.adaptiveLoopEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','adaptive loop disabled');if(mode==='goal'&&(!this.flags.goalEnabled||!this.flags.evaluatorEnforced))throw new SessionAutomationConflictError('FEATURE_DISABLED','goal evaluator is not fail-closed');}
 private assertFence(current:SessionAutomationSnapshot,input:{expectedControlVersion?:number;expectedIncarnationId?:string}):void{if(input.expectedControlVersion!==undefined&&input.expectedControlVersion!==current.controlVersion)throw new SessionAutomationConflictError('STALE_CONTROL_VERSION','controlVersion 已变化',current);if(input.expectedIncarnationId!==undefined&&input.expectedIncarnationId!==current.incarnationId)throw new SessionAutomationConflictError('STALE_CONTROL_VERSION','incarnation 已变化',current);}
}
