import { randomUUID } from 'node:crypto';
import type pg from 'pg';
import type { ModelUsage, RunContext } from './types.js';
import { resolveAutomationBudgetReason } from './sessionAutomationBudgetProgress.js';
import { sessionAutomationTables } from './sessionAutomationStoreSchema.js';

export interface AutomationAttemptHandle { providerAttemptId:string; reservationId:string; sourceKey:string; }

export class AutomationBudgetExceededError extends Error {
  constructor(readonly reason:string){super(`automation budget exhausted: ${reason}`);this.name='AutomationBudgetExceededError';}
}

/** Production fail-closed boundary around automation model/tool side effects. */
export class SessionAutomationRuntimeGuard {
  private readonly tables;
  constructor(private readonly pool:pg.Pool,private readonly tablePrefix='runtime',private readonly runsTable=`${tablePrefix}_runs`){this.tables=sessionAutomationTables(tablePrefix);}
  private lineage(context:RunContext){const fence=context.automationFence;if(!fence)return undefined;const tenantId=context.tenantId;if(!tenantId)throw new Error('automation tenant identity unavailable');return{tenantId,sessionId:context.sessionId,automationId:fence.automationId,incarnationId:fence.incarnationId,generation:fence.generation,executionId:fence.executionId,runId:fence.runId};}
  async barrier(context:RunContext):Promise<void>{const lineage=this.lineage(context);if(!lineage)return;const client=await this.pool.connect();try{await client.query('BEGIN');await client.query(`SELECT automation_id FROM ${this.tables.automations} WHERE tenant_id=$1 AND session_id=$2 AND automation_id=$3 FOR UPDATE`,[lineage.tenantId,lineage.sessionId,lineage.automationId]);const reason=await resolveAutomationBudgetReason({client,tables:this.tables,tablePrefix:this.tablePrefix,runsTable:this.runsTable,tenantId:lineage.tenantId,sessionId:lineage.sessionId,automationId:lineage.automationId});if(reason){await client.query(`UPDATE ${this.tables.automations} SET status='expired',phase='terminal',limit_hit_reason=COALESCE(limit_hit_reason,$3),limit_hit_at=COALESCE(limit_hit_at,now()),next_wakeup_at=NULL,updated_at=now() WHERE tenant_id=$1 AND automation_id=$2`,[lineage.tenantId,lineage.automationId,reason]);await client.query('COMMIT');throw new AutomationBudgetExceededError(reason);}await client.query('COMMIT');}catch(error){await client.query('ROLLBACK').catch(()=>undefined);throw error;}finally{client.release();}}
  async beforeModel(context:RunContext,operation:string):Promise<AutomationAttemptHandle|undefined>{const lineage=this.lineage(context);if(!lineage)return undefined;await this.barrier(context);const client=await this.pool.connect();try{await client.query('BEGIN');const unresolved=await client.query(`SELECT provider_attempt_id,state FROM ${this.tables.providerAttempts} WHERE tenant_id=$1 AND run_id=$2 AND state IN ('prepared','dispatched','result_unknown','reconcile') FOR UPDATE`,[lineage.tenantId,lineage.runId]);if(unresolved.rowCount)throw new Error(`automation provider attempt requires reconciliation: ${unresolved.rows[0].provider_attempt_id}:${unresolved.rows[0].state}`);const prepared=await client.query(`SELECT prepared_dispatch_attempt_id FROM ${this.tables.preparedDispatchAttempts} WHERE tenant_id=$1 AND execution_id=$2 ORDER BY prepared_at LIMIT 1`,[lineage.tenantId,lineage.executionId]);if(!prepared.rows[0])throw new Error('automation prepared dispatch attribution unavailable');const reservationId=randomUUID(),providerAttemptId=randomUUID(),sourceKey=`model:${lineage.runId}:${operation}:${randomUUID()}`;await client.query(`INSERT INTO ${this.tables.budgetReservations}(reservation_id,tenant_id,session_id,automation_id,incarnation_id,generation,execution_id,run_id,budget_kind,amount,unit,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'turns',1,'turn',$9)`,[reservationId,lineage.tenantId,lineage.sessionId,lineage.automationId,lineage.incarnationId,lineage.generation,lineage.executionId,lineage.runId,sourceKey]);await client.query(`INSERT INTO ${this.tables.providerAttempts}(provider_attempt_id,prepared_dispatch_attempt_id,tenant_id,session_id,automation_id,incarnation_id,generation,execution_id,run_id,provider,operation,idempotency_key,request_payload,state,dispatched_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'model',$10,$11,$12,'prepared',NULL)`,[providerAttemptId,prepared.rows[0].prepared_dispatch_attempt_id,lineage.tenantId,lineage.sessionId,lineage.automationId,lineage.incarnationId,lineage.generation,lineage.executionId,lineage.runId,operation,sourceKey,JSON.stringify({model:context.model})]);await client.query(`UPDATE ${this.tables.providerAttempts} SET state='dispatched',version=version+1,dispatched_at=now(),updated_at=now() WHERE provider_attempt_id=$1 AND state='prepared'`,[providerAttemptId]);await client.query('COMMIT');return{providerAttemptId,reservationId,sourceKey};}catch(error){await client.query('ROLLBACK').catch(()=>undefined);throw error;}finally{client.release();}}
  async finishModel(context:RunContext,handle:AutomationAttemptHandle|undefined,usage:ModelUsage|undefined,error?:unknown):Promise<void>{if(!handle)return;const lineage=this.lineage(context)!;const tokens=Object.values(usage??{}).reduce((sum,value)=>sum+(typeof value==='number'?value:0),0);const client=await this.pool.connect();try{await client.query('BEGIN');if(error){await client.query(`UPDATE ${this.tables.providerAttempts} SET state='result_unknown',version=version+1,last_error=$2,updated_at=now() WHERE provider_attempt_id=$1 AND state='dispatched'`,[handle.providerAttemptId,error instanceof Error?error.message:String(error)]);await client.query(`UPDATE ${this.tables.budgetReservations} SET state='result_unknown',version=version+1,updated_at=now() WHERE reservation_id=$1 AND state='reserved'`,[handle.reservationId]);await client.query(`UPDATE ${this.tables.automations} SET status='reconcile_required',phase='waiting',next_wakeup_at=NULL,updated_at=now() WHERE tenant_id=$1 AND session_id=$2 AND automation_id=$3 AND active_run_id=$4`,[lineage.tenantId,lineage.sessionId,lineage.automationId,lineage.runId]);}else{await client.query(`UPDATE ${this.tables.providerAttempts} SET state='completed',version=version+1,result_payload=$2,completed_at=now(),updated_at=now() WHERE provider_attempt_id=$1 AND state='dispatched'`,[handle.providerAttemptId,JSON.stringify({usage:usage??null})]);await client.query(`UPDATE ${this.tables.budgetReservations} SET state='settled',version=version+1,updated_at=now() WHERE reservation_id=$1 AND state='reserved'`,[handle.reservationId]);await client.query(`INSERT INTO ${this.tables.budgetSettlements}(settlement_id,reservation_id,tenant_id,session_id,automation_id,incarnation_id,generation,execution_id,run_id,idempotency_key,amount,outcome,provider_receipt) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,1,'charged',$11)`,[randomUUID(),handle.reservationId,lineage.tenantId,lineage.sessionId,lineage.automationId,lineage.incarnationId,lineage.generation,lineage.executionId,lineage.runId,`settle:${handle.sourceKey}`,JSON.stringify({usage:usage??null})]);await client.query(`INSERT INTO ${this.tables.usage}(usage_id,tenant_id,session_id,automation_id,execution_id,source_key,source_kind,turns,tokens,credits) VALUES($1,$2,$3,$4,$5,$6,'model',1,$7,0) ON CONFLICT(tenant_id,automation_id,source_key) DO NOTHING`,[randomUUID(),lineage.tenantId,lineage.sessionId,lineage.automationId,lineage.executionId,handle.sourceKey,tokens]);}await client.query('COMMIT');}catch(error2){await client.query('ROLLBACK').catch(()=>undefined);throw error2;}finally{client.release();}}
  async recordInteraction(context:RunContext,key:string,kind:string,state:'active'|'completed',payload:Record<string,unknown>):Promise<void>{const l=this.lineage(context);if(!l)return;await this.pool.query(`INSERT INTO ${this.tables.interactions}(interaction_id,tenant_id,session_id,automation_id,incarnation_id,generation,execution_id,run_id,interaction_key,interaction_kind,state,request_payload,response_payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(tenant_id,interaction_key) DO UPDATE SET state=EXCLUDED.state,response_payload=COALESCE(EXCLUDED.response_payload,${this.tables.interactions}.response_payload),version=${this.tables.interactions}.version+1,updated_at=now()`,[randomUUID(),l.tenantId,l.sessionId,l.automationId,l.incarnationId,l.generation,l.executionId,l.runId,key,kind,state,JSON.stringify(payload),state==='completed'?JSON.stringify(payload):null]);}
  async recordBackgroundResource(context:Pick<RunContext,'tenantId'|'sessionId'|'automationFence'>,resourceKey:string,childRunId:string,state:'active'|'released'):Promise<void>{const l=this.lineage(context as RunContext);if(!l)return;await this.pool.query(`INSERT INTO ${this.tables.backgroundResources}(background_resource_id,tenant_id,session_id,automation_id,incarnation_id,generation,execution_id,run_id,resource_kind,resource_key,provider_resource_id,state,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'child_run',$9,$10,$11,$12) ON CONFLICT(tenant_id,resource_kind,resource_key) DO UPDATE SET provider_resource_id=EXCLUDED.provider_resource_id,state=EXCLUDED.state,metadata=EXCLUDED.metadata,version=${this.tables.backgroundResources}.version+1,updated_at=now()`,[randomUUID(),l.tenantId,l.sessionId,l.automationId,l.incarnationId,l.generation,l.executionId,l.runId,resourceKey,childRunId,state,JSON.stringify({childRunId,parentRunId:l.runId})]);}
}
