import { parseSessionAutomationCommand } from '@agent/shared/lib/sessionAutomationCommands.js';
import type { SessionAutomationCommandResponse, SessionAutomationControlAction, SessionAutomationSnapshot } from '@agent/shared/types/sessionAutomation.js';
import { commandDigest, PgSessionAutomationStore, SessionAutomationConflictError, type AutomationIdentity } from './sessionAutomationStore.js';
export interface SessionAutomationFeatureFlags { controlEnabled:boolean;executionEnabled:boolean;fixedLoopEnabled:boolean;adaptiveLoopEnabled:boolean;goalEnabled:boolean;evaluatorEnforced:boolean; }
export const DEFAULT_SESSION_AUTOMATION_FLAGS:SessionAutomationFeatureFlags={controlEnabled:false,executionEnabled:false,fixedLoopEnabled:false,adaptiveLoopEnabled:false,goalEnabled:false,evaluatorEnforced:false};
export class SessionAutomationCommandService {
 constructor(readonly store:PgSessionAutomationStore,readonly flags:SessionAutomationFeatureFlags,readonly cancelRun?:(runId:string,reason:string)=>Promise<void>){}
 async command(id:AutomationIdentity,input:{clientMessageId:string;command:string;expectedControlVersion?:number;expectedIncarnationId?:string}):Promise<SessionAutomationCommandResponse>{
  if(!this.flags.controlEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','Session automation control disabled');
  const parsed=parseSessionAutomationCommand(input.command);if(!parsed)throw new SessionAutomationConflictError('INVALID_COMMAND','不是 automation 命令');
  const digest=commandDigest(input.command);let cancelRunId:string|undefined;
  const result=await this.store.tx(async c=>{const replay=await this.store.findCommand(c,id,input.clientMessageId,digest);if(replay)return {...replay as SessionAutomationCommandResponse,result:'idempotent_replay' as const};
   const live=await this.store.getLive(c,id.tenantId,id.sessionId);let response:SessionAutomationCommandResponse;
   if(parsed.action==='status'||parsed.action==='list'){response={result:'status',snapshot:live};}
   else if(['pause','resume','run','clear','reconcile'].includes(parsed.action)){if(!live)throw new SessionAutomationConflictError('NOT_FOUND','没有活动 automation');this.assertFence(live,input);if((parsed.action==='pause'||parsed.action==='clear')&&live.activeRunId)cancelRunId=live.activeRunId;response={result:'updated',snapshot:await this.store.control(c,live,parsed.action as SessionAutomationControlAction)};}
   else {if (!('spec' in parsed)) throw new SessionAutomationConflictError('INVALID_COMMAND','命令缺少 spec');this.assertFeature(parsed.spec.mode);if(live&&parsed.action==='create')throw new SessionAutomationConflictError('CONFIRM_REPLACE_REQUIRED','已有活动 automation，需显式 replace',live);if(live){this.assertFence(live,input);if(live.activeRunId)cancelRunId=live.activeRunId;response={result:'updated',snapshot:await this.store.replace(c,live,parsed.spec)};}else{response={result:'created',snapshot:await this.store.create(c,id,parsed.spec,new Date())};}}
   await this.store.recordCommand(c,id,id.sessionId,input.clientMessageId,digest,response.snapshot?.automationId,response);return response;});
  if(cancelRunId)await this.cancelRun?.(cancelRunId,'session_automation_control');return result;
 }
 async control(id:AutomationIdentity,automationId:string,input:{clientMessageId:string;action:SessionAutomationControlAction;expectedControlVersion:number;expectedIncarnationId:string}):Promise<SessionAutomationCommandResponse>{
  if(!this.flags.controlEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','Session automation control disabled');const digest=commandDigest(JSON.stringify(input));let cancelRunId:string|undefined;
  const result=await this.store.tx(async c=>{const replay=await this.store.findCommand(c,id,input.clientMessageId,digest);if(replay)return {...replay as SessionAutomationCommandResponse,result:'idempotent_replay' as const};const current=await this.store.getLocked(c,id.tenantId,id.sessionId,automationId);if(!current)throw new SessionAutomationConflictError('NOT_FOUND','automation 不存在');this.assertFence(current,input);if((input.action==='pause'||input.action==='clear')&&current.activeRunId)cancelRunId=current.activeRunId;const response={result:'updated' as const,snapshot:await this.store.control(c,current,input.action)};await this.store.recordCommand(c,id,id.sessionId,input.clientMessageId,digest,automationId,response);return response;});
  if(cancelRunId)await this.cancelRun?.(cancelRunId,'session_automation_control');return result;
 }
 private assertFeature(mode:string):void{if(!this.flags.executionEnabled)throw new SessionAutomationConflictError('EXECUTION_DISABLED','execution kill switch 已关闭');if(mode==='fixed'&&!this.flags.fixedLoopEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','fixed loop disabled');if(mode==='adaptive'&&!this.flags.adaptiveLoopEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','adaptive loop disabled');if(mode==='goal'&&!this.flags.goalEnabled)throw new SessionAutomationConflictError('FEATURE_DISABLED','goal disabled');}
 private assertFence(current:SessionAutomationSnapshot,input:{expectedControlVersion?:number;expectedIncarnationId?:string}):void{if(input.expectedControlVersion!==undefined&&input.expectedControlVersion!==current.controlVersion)throw new SessionAutomationConflictError('STALE_CONTROL_VERSION','controlVersion 已变化',current);if(input.expectedIncarnationId!==undefined&&input.expectedIncarnationId!==current.incarnationId)throw new SessionAutomationConflictError('STALE_CONTROL_VERSION','incarnation 已变化',current);}
}
