import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { PgEventStore } from './pgEventStore.js';
import { PgRunStore } from './runStore.js';
import { PgSessionAutomationStore } from './sessionAutomationStore.js';
import { SessionAutomationTerminalProjector } from './sessionAutomationTerminalProjector.js';
import { SessionAutomationToolProvider } from '../agent/tools/sessionAutomationTools.js';
const {Pool}=pg;
const url=process.env.TEST_DATABASE_URL;
const describePg=url?describe:describe.skip; // schema text tests still run without PG

describePg('session automation real PostgreSQL integration',()=>{
 const prefix=`automation_${randomUUID().replaceAll('-','').slice(0,12)}`;let pool:InstanceType<typeof Pool>;let events:PgEventStore;let runs:PgRunStore;let store:PgSessionAutomationStore;const tenant='tenant-a',session='session-a',automation=randomUUID(),incarnation=randomUUID();
 beforeAll(async()=>{pool=new Pool({connectionString:url!,max:8});events=new PgEventStore({connectionString:url!,tablePrefix:prefix,poolMax:4});await events.init();runs=new PgRunStore({pool,tablePrefix:prefix});await runs.init();store=new PgSessionAutomationStore(pool,prefix,runs.runsTable);await store.init();await pool.query(`INSERT INTO ${store.tables.automations}(automation_id,tenant_id,session_id,owner_user_id,incarnation_id,kind,mode,status,generation,spec_version,control_version,projection_version) VALUES($1,$2,$3,'user-a',$4,'loop','adaptive','active',1,1,1,1)`,[automation,tenant,session,incarnation]);await pool.query(`INSERT INTO ${store.tables.specs}(automation_id,tenant_id,session_id,spec_version,spec_digest,spec) VALUES($1,$2,$3,1,'digest',$4)`,[automation,tenant,session,JSON.stringify({kind:'loop',mode:'adaptive',prompt:'continue',budget:{}})]);},30_000);
 afterAll(async()=>{if(!pool)return;await events.close();await pool.query(`DO $$ DECLARE r record; BEGIN FOR r IN SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename LIKE '${prefix}_%' LOOP EXECUTE format('DROP TABLE IF EXISTS %I CASCADE',r.tablename); END LOOP; END $$`).catch(()=>undefined);await pool.end();},30_000);
 async function wake(key:string,generation=1){await store.tx(c=>store.scheduleTx(c,{tenantId:tenant,sessionId:session,automationId:automation,incarnationId:incarnation,generation,specVersion:1,continuationEpoch:1,triggerKey:key,dueAt:new Date(0),payload:{}}));}
 it('multi-worker claims exactly once and crash lease is recovered',async()=>{await wake('multi');await Promise.all([store.claimDue(10,10),store.claimDue(10,10)]);const [a,b]=await Promise.all([store.claimDispatch(10,10),store.claimDispatch(10,10)]);expect([...a,...b]).toHaveLength(1);await new Promise(r=>setTimeout(r,20));await store.recoverLeases();expect(await store.claimDispatch(10,1000)).toHaveLength(1);});
 it('cancel/generation fence prevents stale dispatch',async()=>{await pool.query(`UPDATE ${store.tables.outbox} SET state='dead'`);await wake('old-generation');await store.claimDue();await pool.query(`UPDATE ${store.tables.automations} SET generation=2,status='cancelled' WHERE automation_id=$1`,[automation]);expect(await store.claimDispatch()).toEqual([]);});
 it('tool visibility requires matching host fence',()=>{const provider=new SessionAutomationToolProvider({} as never);expect(provider.list()).toEqual([]);const base={channelContext:{channel:'web'},workspace:{root:'.',executionTarget:'server-local'},sessionId:session,runId:'run-a'} as any;expect(provider.list(base)).toEqual([]);expect(provider.list({...base,automationFence:{automationId:automation,incarnationId:incarnation,generation:2,specVersion:1,executionId:'e',runId:'run-a'}}).map(t=>t.id)).toEqual(['ScheduleWakeup','UpdateGoal']);});
 it('terminal recovery scan advances durable cursor and survives restart',async()=>{await pool.query(`UPDATE ${store.tables.automations} SET generation=3,status='active',mode='adaptive',active_run_id=NULL WHERE automation_id=$1`,[automation]);await wake('terminal',3);await store.claimDue();const [dispatch]=await store.claimDispatch();await runs.createPending({runId:dispatch!.targetRunId,sessionId:session,tenantId:tenant,userId:'user-a',metadata:{schedulerState:'staged'}});await store.markDispatched(dispatch!);await events.append({type:'run_finished',runId:dispatch!.targetRunId,sessionId:session,subtype:'success',numTurns:1},{tenantId:tenant});const first=new SessionAutomationTerminalProjector(store);expect(await first.recover(events)).toBeGreaterThan(0);const cursor=await first.cursor();const second=new SessionAutomationTerminalProjector(store);expect(await second.recover(events)).toBe(0);expect(await second.cursor()).toBe(cursor);const execution=await pool.query(`SELECT state,terminal_status FROM ${store.tables.executions} WHERE run_id=$1`,[dispatch!.targetRunId]);expect(execution.rows[0]).toMatchObject({state:'terminal',terminal_status:'completed'});});
});
