import { describe,expect,it,vi } from 'vitest';
import { parseAutomationDuration,parseSessionAutomationCommand,SessionAutomationParseError } from './sessionAutomationCommands.js';
describe('session automation command parser',()=>{
 it('parses fixed loop and strict interval',()=>{expect(parseSessionAutomationCommand('/loop 5m --max-runs 3 -- check CI')).toMatchObject({family:'loop',action:'create',spec:{mode:'fixed',intervalMs:300000,prompt:'check CI',budget:{maxRuns:3}}});expect(()=>parseAutomationDuration('59s')).toThrow(SessionAutomationParseError);});
 it('keeps management words literal after --',()=>{expect(parseSessionAutomationCommand('/loop -- status')).toMatchObject({action:'create',spec:{mode:'adaptive',prompt:'status'}});expect(parseSessionAutomationCommand('/goal -- pause')).toMatchObject({action:'create',spec:{condition:'pause'}});expect(parseSessionAutomationCommand('/goal -- status')).toMatchObject({action:'create',spec:{condition:'status'}});});
 it('treats bare and explicit goal status as control status and clear aliases consistently',()=>{expect(parseSessionAutomationCommand('/goal')).toEqual({family:'goal',action:'status'});expect(parseSessionAutomationCommand('/goal status')).toEqual({family:'goal',action:'status'});expect(parseSessionAutomationCommand('/goal cancel')).toEqual({family:'goal',action:'clear'});});
 it('applies a hard default budget only to otherwise unbounded goals',()=>{expect(parseSessionAutomationCommand('/goal ship it')).toMatchObject({spec:{budget:{maxTurns:20,maxTokens:250000}}});expect(parseSessionAutomationCommand('/goal --max-runs 2 -- ship it')).toMatchObject({spec:{budget:{maxRuns:2}}});expect(parseSessionAutomationCommand('/loop keep watching')).toMatchObject({spec:{budget:{}}});});
 it('parses goal budget',()=>{vi.setSystemTime(new Date('2026-01-01T00:00:00Z'));expect(parseSessionAutomationCommand('/goal set --max-turns 20 --max-tokens 250k --for 8h -- tests pass')).toMatchObject({action:'create',spec:{condition:'tests pass',budget:{maxTurns:20,maxTokens:250000,expiresAt:'2026-01-01T08:00:00.000Z'}}});vi.useRealTimers();});
 it('rejects empty/oversized goal and unknown flags',()=>{expect(()=>parseSessionAutomationCommand('/goal set --')).toThrow();expect(()=>parseSessionAutomationCommand('/loop --wat x')).toThrow();expect(()=>parseSessionAutomationCommand(`/goal ${'x'.repeat(16001)}`)).toThrow();});
});
